pages/accountLists/[accountListId]/contacts.test.tsx, src/components/Task/Drawer/Drawer.tsx, src/components/Task/Drawer/Form/Form.mock.tsx, src/components/Task/Drawer/Form/Form.stories.tsx, src/components/Task/Drawer/Form/Form.test.tsx, src/components/Task/Drawer/Form/Form.tsx, src/components/Task/Drawer/Form/TaskDrawer.graphql, src/components/Task/List/List.test.tsx, src/components/Task/List/List.tsx, src/theme.ts
@OzzieOrca and I discussed this on slack, but in order to remove the task from the apollo cache after deleting it(to avoid having to query all tasks again), I had to pass down the ```filter``` and the ```rowsPerPage``` in order to correctly query the data from the cache. 
I haven't added stories or tests yet for this new logic as I wanted to get others' opinions first on this implementation and see if anyone has any suggestions for improvement.
=> MPDX-6944-Add-Delete-Button-Task-Detail-Drawer

pages/api/graphql-rest.page.ts, src/components/Dashboard/ThisWeek/NewsletterMenu.graphql, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.stories.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/GetNewsletterContacts.graphql, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportPhysical/ExportPhysical.stories.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportPhysical/ExportPhysical.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportPhysical/ExportPhysical.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.stories.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/NewsletterMenu.graphql, src/components/Dashboard/ThisWeek/NewsletterMenu/NewsletterMenu.stories.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/NewsletterMenu.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/NewsletterMenu.tsx, src/components/Dashboard/ThisWeek/ThisWeek.tsx
So this ticket adds functionality to the newsletter menu, but to a certain degree. This menu has three dropdown options:
1. Log Newsletter
2. Export Email
3. Export Physical
Only "Export Email" has full functionality and design in this PR, and I plan to create separate tickets/prs to address the other two. I did this as I didn't want the pr to get too large. "Log Newsletter" and "Export Physical" are just the barebones for those dialogs and tests.  Let me know what you think and if you have any questions 🙂
=> MPDX-6943-Add-Newsletter-Dropdown-Functionality

src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx, src/components/Layouts/Primary/TopBar/TopBar.tsx
I noticed these warnings in the console while working on another PR. It's from my previous work on https://github.com/CruGlobal/mpdx-react/pull/28. This PR just adds the ```item``` attribute to fix the warnings in the console, styling remains unaffected.
=> Nav-Menu-Grid-Fix

src/components/Task/Drawer/Form/Form.test.tsx, src/components/Task/Drawer/Form/Form.tsx
This PR aims to fix a bug that occurs when trying to update the cache after deleting a task. This bug was introduced in the [PR](https://github.com/CruGlobal/mpdx-react/pull/40) that added the ability to delete tasks. The main reason for this bug is the fact that the task drawer can be opened from a couple of different places throughout the app. The main two places are on the dashboard and on the task page. My logic to delete a task and then update the cache after only took into account deleting on the task page, where the query ```GetTasksForTaskListQuery``` would have been called. However, there is a scenario where the user could delete a task on the dashboard, without ever going to the tasks page, therefore ```GetTasksForTaskListQuery``` has not been called, and trying to update the …
=> Fix-Delete-Task-and-Update-Cache-Bug

src/components/Dashboard/ThisWeek/LateCommitments/LateCommitments.stories.tsx, src/components/Dashboard/ThisWeek/LateCommitments/LateCommitments.test.tsx, src/components/Dashboard/ThisWeek/LateCommitments/LateCommitments.tsx, src/components/Dashboard/ThisWeek/LateCommitments/index.tsx, src/components/Dashboard/ThisWeek/ThisWeek.tsx
Noticed that the days for the late commitments weren't being rounded.
Went ahead and switched to named exports and the styled API while I was as it 🙂
=> Fix-Dashboard-Late-Commitment-Dates

src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.tsx, src/components/Task/Drawer/Form/Form.tsx
I assumed that we did not need this to be required in the task schema, as the api will automatically set it to false upon task creation(?). It also looks like we aren't currently grabbing the ```starred``` field in the query ```GetTaskForTaskDrawer```, so it was preventing that update of the task. Not sure if that field needs to be added. It also wasn't set in the ```initialTask``` values we use when creating a new task, but I assume the api will set that field upon the task creation so it feels like extra work for the client to set it.
=> Remove-Duplicate-Starred-Definition-in-TaskSchema

src/components/Task/Drawer/Form/Form.test.tsx, src/components/Task/Drawer/Form/Form.tsx
I noticed yesterday that the remove button always shows in the task drawer, even when creating a new task... I missed this in the initial implementation! Now it will only display if a task is passed into the task drawer(meaning they are currently completing or editing an existing task).
=> Only show remove button if task id exist

pages/api/Schema/index.ts, pages/api/Schema/reports/expectedMonthlyTotal/datahandler.ts, pages/api/Schema/reports/expectedMonthlyTotal/expectedMonthlyTotal.graphql, pages/api/Schema/reports/expectedMonthlyTotal/resolvers.ts, pages/api/graphql-rest.page.ts
Here's the query I was using to test this:
```graphql
query ExpectedMonthlyTotalReport($accountListId: ID!) {
expectedMonthlyTotalReport(accountListId: $accountListId) {
received {
donations {
...Donation
}
total
}
likely {
donations {
...Donation
}
total
}
unlikely {
donations {
...Donation
}
total
}
currency
currencySymbol
}
}
fragment Donation on ExpectedMonthlyTotalDonation {
contactId
contactName
contactStatus
convertedAmount
convertedCurrency
convertedCurrencySymbol
donationAmount
donationCurrency
donationCurrencySymbol
pledgeAmount
pledgeCurrency
pledgeCurrencySymbol
pledgeFrequency
}
```
=> MPDX-7048: Expected Monthly Total Report - REST to GraphQL

src/components/Layouts/SidePanelsLayout.tsx
So I just realized for the first time today as I was trying to scroll down to the mailing section of the contact details tab... that I couldn't actually scroll lol. This was true for the whole right panel. Adding this scroll box around the right panel seemed to fix that, but let me know if there's a better way to wrap this.
=> Fix-Contact-Right-Panel-Scroll

src/components/Layouts/Basic/TopBar/TopBar.tsx
I'm genuinely not sure what the purpose of the additional `AppBar` was, but it was causing the page to needlessly extend beyond the height of the browser. Feel free to yell at me to put it back.
=> MPDX-6919 - Removing vertical scrollbar

src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/ContactDetailsTabMailing.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/ContactDetailsTabMailing.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/ContactMailing.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddress.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/ContactOther.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/EditContactOtherModal/EditContactOtherModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/EditContactOtherModal/EditContactOtherModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/ContactPeople.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetailsModal.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetailsModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetailsModal.tsx
I think I'm going to handle deleting and creating addresses in a separate pr. This PR focuses on rendering all contact addresses and allowing the editing of said addresses. There wasn't a design for this modal so I based it on the current design. Also made some adjustments to help make the separation of addresses clearer in the UI. The first commit is a little bit of a mess, sorry. It adds the rendering of all addresses instead of just the primary. While I was working on it, I realized I had not been using the fragment types for my other modal components so I updated them all to help simplify types.
=> MPDX-6998-Edit-Contact-Addresses

src/components/Layouts/Primary/Primary.test.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx, src/components/Layouts/Primary/TopBar/TopBar.test.tsx, src/components/Layouts/Primary/TopBar/TopBar.tsx
This bug was occurring because on certain pages, the state from ```useApp``` did not contain the ```accountListId```. We are moving away from putting stuff in this global state. I'm going to try to clean up other places that still use this in a separate pr but unfortunately, more components are using this than I thought...
=> Fix-Navbar-Visibility-Bug

pages/_app.page.tsx, src/components/App/Context.ts, src/components/App/Provider.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/ContactTaskRow.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/ContactTaskRow.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.tsx, src/components/Dashboard/Dashboard.test.tsx, src/components/Dashboard/ThisWeek/PartnerCare/PartnerCare.test.tsx, src/components/Dashboard/ThisWeek/PartnerCare/PartnerCare.tsx, src/components/Dashboard/ThisWeek/TasksDueThisWeek/TasksDueThisWeek.test.tsx, src/components/Dashboard/ThisWeek/TasksDueThisWeek/TasksDueThisWeek.tsx, src/components/Dashboard/ThisWeek/ThisWeek.test.tsx, src/components/Layouts/Primary/AddFab/AddFab.test.tsx, src/components/Layouts/Primary/AddFab/AddFab.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/AddMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/AddMenu.tsx, src/components/Task/Drawer/CompleteForm/CompleteForm.test.tsx, src/components/Task/Drawer/CompleteForm/CompleteForm.tsx, src/components/Task/Drawer/TaskDrawerContext.ts, src/components/Task/Drawer/TaskDrawerProvider.tsx, src/components/Task/List/List.test.tsx, src/components/Task/List/List.tsx, src/components/Task/Status/Status.test.tsx, src/components/Task/Status/Status.tsx, src/hooks/useTaskDrawer.tsx
Slowly getting rid of ```useApp```, piece by piece 🙂 We determined that the task drawer state/logic still has to exist in a context that is accessible, so now it's in its own context instead of a global one.
=> Remove-openTaskDrawer

pages/api/Schema/reports/designationAccounts/datahandler.ts, pages/api/Schema/reports/designationAccounts/designationAccounts.graphql
Spencer added a DesignationAccount type to the Rails GraphQL schema. I'm just renaming this to get our server working again. We'll need to reconcile these eventually.
=> Rename DesignationAccount Rest GraphQL type due to conflict with API

src/components/Contacts/ContactDetails/ContactDetails.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx
Small random pr, sorry 🙂 I noticed a few issues with deleting a contact while working on removing ```useApp```. Those issues were:
1. the delete contact modal would not close after deleting the contact.
2. the contact details side panel would remain open even after deleting.
So I went ahead and quickly fixed that. Sorry for missing it initially!
=> Improve-Contact-Deletion-Logic

pages/accountLists/[accountListId]/tools/fixEmailAddresses.page.tsx, src/components/Tool/FixEmailAddresses/Contact.test.tsx, src/components/Tool/FixEmailAddresses/Contact.tsx, src/components/Tool/FixEmailAddresses/DeleteModal.test.tsx, src/components/Tool/FixEmailAddresses/DeleteModal.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddreses.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx, src/components/Tool/FixEmailAddresses/NoContacts.test.tsx, src/components/Tool/FixEmailAddresses/NoContacts.tsx
- Removed side bar
- Looks similar to fixing mailing addresses but there is some functionality, adding an new email, deleting one and changing primary, the incoming data is stored in the component state, then mutations update the state. When the user clicks confirm, a gql mutation will be made so it should work in the future without too much tweaking.
- Very similar to the fix phone numbers so will wait for this one to get approved first
Adding emails and changing primary:
Mobile View:
=> Fix email addresses basic UI

pages/accountLists/[accountListId]/tools/appeals.page.tsx, src/components/Tool/Appeal/AddAppealForm.tsx, src/components/Tool/FixCommitmentInfo/FixCommitmentInfo.tsx, src/components/Tool/FixMailingAddresses/Contact.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx, src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx, src/components/Tool/Home/Home.tsx, src/components/Tool/Home/Tool.tsx
Removed the sidebar for the tools pages, except the appeal details page, I think we should discuss more for this page because it feels nice being able to toggle between the views without having to click on the top bar.
Also fixed some of the responsiveness for some of the tools pages
=> removed sidebar, decreased content width and centered it

src/components/Contacts/ContactDetails/ContactDontationsTab/ContactDonationsTab.graphql, src/components/Contacts/ContactDetails/ContactDontationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.graphql, src/components/Contacts/ContactDetails/ContactDontationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDontationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/ContactDetails/ContactDontationsTab/PartnershipInfo/PartnershipInfo.tsx
This was a bit complicated to work on, more so than I initially thought lol. What's complicated is that you have to persist the data as the user searches for new contacts, as the data is continually changing because of the auto-complete component. And then if they decide to delete a contact referral that was already created, I had to figure out a way to remove it from the UI, but still persist it as it's not truly removed until ```destroyed``` is set to ```true``` and is sent to the api. There's just a lot of moving parts and pieces. Feel free to try it out and make sure it works. I tried to cover all the scenarios but maybe I missed something 🙂 I'll be adding tests in a separate commit as I wanted others to take an initial look at the logic for this.
=> MPDX-7121-Add-Ability-To-Edit-ReferredBy-In-Edit-Partnership-Modal

src/lib/client.ts
- `assumeImmutableResults` is still false by default but `freezeResults` has been defaulted to true by Apollo 3.0
- https://www.apollographql.com/blog/announcement/previewing-the-apollo-client-3-cache-565fadd6a01e/#additional-cache-improvements
- https://www.apollographql.com/blog/announcement/frontend/whats-new-in-apollo-client-2-6/#enforcing-immutability
- `assumeImmutableResults` is still `false` by default https://github.com/apollographql/apollo-client/blob/d3a74ec87cee2b9819a7bb5f2be605c14857aa28/src/core/ApolloClient.ts#L158
=> Enable Apollo assumeImmutableResults

src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx
Added limit to the notifications to 9. If there is more than 9 it will show 9+ (like in the original app)
=> Tools notificattion limit

src/components/Contacts/ContactFilters/ContactFilters.mocks.ts, src/components/Contacts/ContactFilters/ContactFilters.test.tsx, src/components/Contacts/ContactFilters/ContactFilters.tsx
I did a couple of different things in this pr:
1. Add logic to show featured filters and hide the rest in the "See more filters" section.
2. Fixed some logic that was causing selected filters not to show up outside of the "See more filters" section.
3. Added logic to show the number of selected options per filter.
4. Fixed the clear all logic as it wasn't updating the filters and results correctly.
I'm not sure if the currently featured filters are the ones that are actually wanted. I didn't see those specified in Figma, but maybe I missed it 🤷‍♂️
=> MPDX-7152-Contact-and-Tasks-Show-Featured-Filters

src/lib/client.ts
https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies
Chris ran into an issue where a query for the tools nav menu was stored in the cache. When the actual tools page loaded, no query was sent. I'm a little confused why it still went to the cache even though there were fields missing and should have sent a network request for the missing fields.
I think this will be a better default in general, especially with a persisted cache on production and is what we had in missionhub-react-native. Guess I assumed this was already setup.
=> Change Apollo fetchPolicy to cache-and-network

pages/_document.page.tsx
Some more improvements to RUM here:
- Upgraded from v4 to v5. See all changes from v4 to v5 [here](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#from-v4-to-v5). Some main benefits include:
- Collection of the new INP (Interaction to Next Paint) core web vital
- A side effect of upgrading to v5 is that we no longer have to manually call `startSessionReplayRecording()`
- Automatic collection of user frustration metrics
- Automatic sending of OpenTelemetry when connecting to APM
- To connect RUM and APM, I added the `allowedTracingUrls` configuration
=> No-Jira - Bump RUM version

pages/api/handoff.page.test.ts, pages/api/handoff.page.ts
https://secure.helpscout.net/conversation/2580546553/1144092?folderId=7296147
Fixing error when redirected back to old MPDx after impersonating - Ensuerung the Impersonators accountListId is used.
=> HS 1144092 - Fixing error of setting wrong accountList when impersonating

pages/accountLists/[accountListId]/settings/organizations.page.tsx, pages/accountLists/[accountListId]/settings/organizations/accountLists.page.test.tsx, pages/accountLists/[accountListId]/settings/organizations/accountLists.page.tsx, pages/accountLists/[accountListId]/settings/organizations/contacts.page.test.tsx, pages/accountLists/[accountListId]/settings/organizations/contacts.page.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenu.graphql, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenu.test.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenu.tsx
[HelpScout issue](https://secure.helpscout.net/conversation/2578696149/1142757?folderId=7296147)
The Organization links are only shown if the user is an admin. However, on the old MPDx, users who weren't admins but managed at least one organization could see the page.
This PR allows users who manage an organization and aren't an admin to view the links and visit the page.
=> HS-1142757 - Organizations links on Settings aren't rendering correctly

pages/accountLists/[accountListId]/settings/organizations/accountLists.page.tsx, pages/api/Schema/Settings/Organizations/SearchOrganizationsAccountLists/SearchOrganizationsAccountLists.graphql, pages/api/Schema/Settings/Organizations/SearchOrganizationsAccountLists/resolvers.ts, pages/api/graphql-rest.page.ts, src/components/Settings/Organization/AccountLists/AccountLists.tsx
[MPDX-7891](https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-7891)
Allow contact search on the Organization Accounts page without an organization being selected. I added this to speed up the search, but the admin needs to search contacts without an organization being selected for a broader search.
=> MPDX-7891 - Allow contact search on Organization Accounts without organization selected

src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.test.tsx, src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.tsx
Fixing error introduced in https://github.com/CruGlobal/mpdx-react/pull/891
Currently, on Connect Services, users aren't able to add offline organizations due to the `disableNewUsers` returning as `NULL` from GraphQL.
The issue was caused by a FormIk client error. I've enabled `disableNewUsers` to be nullable and added a test to ensure `NULL` is treated the same way as `TRUE`.
=> MPDX-7893 - Allowing users to add offline organizations to their accounts

src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx
Fixes the `MUI: The Menu component doesn't accept a Fragment as a child.` error introduced in #925.
=> [no-Jira] Fix MUI menu component error

src/components/Settings/integrations/Organization/OrganizationAccordion.test.tsx, src/components/Settings/integrations/Organization/OrganizationAccordion.tsx
[HelpScout ticket](https://secure.helpscout.net/conversation/2583630493/1145680?folderId=7296147)
On Connect Services, the organization modals "OrganizationImportDataSyncModal", "OrganizationEditAccountModal" etc. were always defaulting to the first organization.
This fix ensures if the users have multiple organizations, the organization selected is the organization referred to in the modals.
Changed the deleted text to ensure the user understands which organization they are deleting.
=> MPDX-7892 - Connect Services organization modals referring to incorrect organization

src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/ContactDonationsTab.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/DonationsGraph/DonationsGraph.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.tsx
When Apollo queries are executed, `data` will be the cached data, but `loading` will still be `true` until the network request completes and the freshest data is available. Any time we show a loading spinner or skeleton when `loading` is true, we are ignoring the cached data that is already available. This PR makes the components in the contact details panel display cached data immediately if it is available.
=> [no-Jira] Display cached contact details data immediately

src/components/Settings/integrations/Google/GoogleAccordion.tsx
When `googleAccounts?.length` evaluates to `0`, it would render a literal zero character instead of nothing.
=> [no-Jira] Fix 0 rendered next to Add Google Account button

src/components/Contacts/MassActions/Merge/MassActionsMergeModal.test.tsx, src/components/Contacts/MassActions/Merge/MassActionsMergeModal.tsx
Limiting the number of contacts a user can merge together prevents an [issue like this](https://secure.helpscout.net/conversation/2594181084/1154070/) from happening again.
I've added a limit of eight contacts. I've also added tests to ensure the functionality works.
=> HelpScout - 1154070 - Limit contact merge

src/components/HandoffLink/HandoffLink.test.tsx, src/components/HandoffLink/HandoffLink.tsx, src/components/Settings/preferences/accordions/EarlyAdopterAccordion/EarlyAdopterAccordion.test.tsx, src/components/Settings/preferences/accordions/EarlyAdopterAccordion/EarlyAdopterAccordion.tsx, src/components/User/Preferences/UserPreferenceProvider.test.tsx, src/components/User/Preferences/UserPreferenceProvider.tsx, src/components/common/DateTimePickers/DateTimeFieldPair.test.tsx, src/components/common/DateTimePickers/DesktopDateField.test.tsx, src/components/common/DateTimePickers/DesktopTimeField.test.tsx
This pull request updates the user handover process by ensuring the correct user ID is sent. It modifies the user preferences context to include the user ID, ensuring that all relevant components use this updated information.
- Added `userId` to the `userPreference` context.
- Updated handoff link to utilize the new `userId` from `userPreferences`.
- Revised all relevant components to use `userId` from `userPreferencesContext`.
- Updated tests
=> Hs 1166672 send correct user id on handover

src/components/Contacts/ContactDetails/ContactDetailsTab/StyledComponents.ts, src/components/Tool/FixMailingAddresses/Contact.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx
- This pull request focuses on cleaning up styles on the Fix Mailing Addresses page and components to enhance visual consistency and code maintainability.
- Added an `LockIcon` styled component.
- Fixed styling for individual contact elements.
- Updated the overall page styling to improve layout and appearance.
=> MPDX-7930 - Clean Up Styles on Fix Mailing Addresses

src/lib/intlFormat.test.ts, src/lib/intlFormat.ts
Please make a note of the following text:
This pull request addresses the issue of a blank screen appearing on the contact details tab within a contact.
The problem stems from a date format function called `dateFromParts`. This function lacks the capability to handle an invalid date, resulting in an error when attempting to convert it into a date.
I resolved this issue by implementing error handling within the function and included a test to verify the correct functionality of the fix.
=> Helpscout - Fixing blank screen error on contact details

src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/PersonBirthday/PersonBirthday.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/PersonModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/PersonShowMore/PersonShowMore.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/personModalHelper.tsx, src/components/common/DateTimePickers/CustomDateField.tsx, src/components/common/DateTimePickers/DesktopDateField.test.tsx, src/components/common/DateTimePickers/DesktopDateField.tsx, src/lib/intlFormat.test.ts, src/lib/intlFormat.ts
This pull request follows the pull request at https://github.com/CruGlobal/mpdx-react/pull/961. In this pull request, we ensure that the Person Modal displays an error for invalid dates in order to prompt the user to make the necessary corrections.
Without this update, the input fields will remain empty and retain the incorrect values. This change will ensure that the invalid values are corrected.
=> Helpscout - Show invalid date in person modal with error to fix

amplify.yml, codegen.yml
Amplify Previews are currently not building and deploying due to an error when building.
The error is because we're hitting the staging API when building the GraphQL and since our graphQL doesn't have the Task Phases changes in it, it causes an error.
Fix: Hit the production API when creating the GraphQL, then in the app call the staging API
=> MPDX-7999 - Fix Amplify previews build

pages/accountLists/[accountListId]/tools/appeals.page.tsx, src/components/Tool/Appeal/AddAppealForm.tsx, src/components/Tool/Appeal/Appeal.test.tsx, src/components/Tool/Appeal/Appeal.tsx, src/components/Tool/Appeal/AppealDetails/AppealDetailsHeader.tsx, src/components/Tool/Appeal/AppealProgressBar.tsx, src/components/Tool/Appeal/Appeals.tsx, src/components/Tool/Appeal/CreateAppeal.graphql, src/components/Tool/Appeal/NoAppeal.test.tsx, src/components/Tool/Appeal/NoAppeals.tsx
This PR focuses on rebuilding the UI for the Appeals initial page. The updates include simplifying the code, improving the user experience, and enhancing the functionality of the Appeals page.
- Simplified code and improvements to the left side of the Appeals initial page.
- Display skeletons while Appeals loads, improving the user experience during data fetching.
- Added `ToolsWrapper` to the Appeals initial page.
- Enhanced the Add Appeal form by:
- Implementing Formik for form handling instead of using state.
- Displaying skeletons while statuses and tags load, improving the user experience during data fetching.
I have not written tests for this, as this will come later. **This PR is purely for UI on the initial appeals page.**
=> MPDX-7948 Rebuilding the UI - Appeals initial page

src/components/Tool/MergeContacts/ContactPair.tsx, src/components/Tool/MergeContacts/MergeContacts.test.tsx, src/components/Tool/MergeContacts/MergeContacts.tsx, src/components/Tool/MergeContacts/MergeContactsMock.ts, src/components/Tool/MergeContacts/mergeDuplicatesHelper.ts, src/components/Tool/MergePeople/GetPersonDuplicates.graphql, src/components/Tool/MergePeople/MergePeople.test.tsx, src/components/Tool/MergePeople/MergePeople.tsx, src/components/Tool/MergePeople/PersonDuplicatesMock.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8008#
- Add `updateDuplicate` mutation
- Pass the `id` of the duplicate up to the `updateDuplicate` mutation
- Add `handleBulkUpdateDuplicates()` to loop over duplicates that get ignored and also do the merge mutation
=> MPDX-8008 Ignore duplicates for Merge Contact & Merge People

src/components/Constants/LoadConstants.graphql, src/components/Constants/UseApiConstants.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.tsx, src/components/Contacts/ContactFlow/ContactFlowColumn/ContactFlowColumn.tsx, src/components/Contacts/MassActions/EditFields/MassActionsEditFieldsModal.tsx, src/components/EditDonationModal/EditDonationModal.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/AddDonation/AddDonation.tsx, src/components/Reports/FourteenMonthReports/FourteenMonthReport.tsx, src/components/Reports/FourteenMonthReports/Layout/Table/Table.tsx, src/components/Settings/preferences/accordions/CurrencyAccordion/CurrencyAccordion.test.tsx, src/components/Settings/preferences/accordions/CurrencyAccordion/CurrencyAccordion.tsx
https://cru-main.slack.com/archives/CG47BDCG6/p1718309741203709
- Rename constants that were changed on the API.
oldType -> newType [EXAMPLE]
sendNewsletterOptions -> newsletter
pledgeCurrencies -> pledgeCurrency
pledgeFrequencies -> pledgeFrequency
statuses -> status
likelyToGiveOptions -> likelyToGive
=> No-Jira Update contants names

src/components/Tool/FixSendNewsletter/Contact.test.tsx, src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx, src/components/Tool/FixSendNewsletter/GetInvalidNewsletter.graphql
[Jira](https://jira.cru.org/browse/MPDX-8021)
This PR fixes the initial dropdown values on the fix send newsletter tool to match what the Angular app did:
If primary address: Physical
If primary address and primary email: Both
If no primary address and has primary email: Email
If neither: None
If the opt-out of email newsletters is checked, primary email does not count towards above.
=> MPDX-8021 - Fix Send Newsletter dropdown initial values

src/components/Tool/FixSendNewsletter/FindSendNewsletter.test.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx, src/components/Tool/FixSendNewsletter/GetInvalidNewsletter.graphql
This PR updates the display of contact status to the friendly name instead of the enum id.
=> MPDX-8022 - Fix Send Newsletter: Contact Status Display Value

src/lib/intlFormat.test.ts, src/lib/intlFormat.ts
In this PR, I've fixed an error that happens when the currency is not defined. If the currency is not defined, it shows the white screen of death.
I've ensured the currency is defined and that even if it fails, it will return some value to prevent the white screen of death from happening.
HelpScout issue: https://secure.helpscout.net/conversation/2666844539/1199960?folderId=7296147
- Impersonate the user in question.
- Navigate to contacts and click on the contact with the last name "Dose"
- Click on the donations tab in the contact drawer.
- The donations should now show without an error.
=> HelpScout 1199960 - Fixing intlFormat.ts error when currency is not defined

src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.tsx
In this PR, I removed the functionality to refresh the page after deletion and instead updated the cache to remove the contact in question. I also improved the way we update the cache and tests.
=> HelpScout 1199118 Update cache after contact deletion to prevent refresh

src/components/Contacts/ContactRow/ContactRow.tsx
The goal is to optimize the rendering of InfiniteList. One issue was that the contacts list was defining its components inside of another component, causing them to be unmounted and remounted on every render.
It's a little hard to tell in the screen capture, but it appears that there is more whitespace at the bottom when scrolling in the old version.
https://github.com/CruGlobal/mpdx-react/assets/3740187/13d9ae33-4679-42e7-98bd-b817415fd8f5
https://github.com/CruGlobal/mpdx-react/assets/3740187/06ba455d-b85b-45b7-8f60-85dd4bdccfa1
The `InfiniteList` `EmptyPlaceholder` should also be a stable component function, but I ran out of time to fix that.
@caleballdrin Do you want to test this out and see if it helps improve things?
=> [no-Jira] Move InfiniteList components outside of ContactRow

src/components/Tool/FixSendNewsletter/Contact.test.tsx, src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.test.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletterMock.ts, src/components/Tool/FixSendNewsletter/InvalidNewsletter.graphql
This PR implements the Confirm All button for the Fix Send Newsletter tool.
[Jira](https://jira.cru.org/browse/MPDX-8024)
=> MPDX-8024 - Fix Send Newsletter - Confirm All Button

src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx, src/components/Tool/FixMailingAddresses/GetInvalidAddresses.graphql
* Remove duplicate UpdateContactAddress mutation definition. It was causing errors in the Apollo VS Code extension. Cmd+click to jump to definition in `.graphql` files should work again.
=> [no-Jira] Remove duplicate GraphQL operation

src/components/Tool/Appeal/AppealDetails/AppealHeaderInfo.tsx, src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/DynamicEditAppealHeaderInfoModal.tsx, src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/EditAppeal.graphql, src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/EditAppealHeaderInfoModal.test.tsx, src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/EditAppealHeaderInfoModal.tsx, src/components/Tool/Appeal/AppealsDetailsPage.test.tsx, src/components/Tool/Appeal/List/ContactsList/ContactsList.tsx
In this PR, I added a modal that allows the user to edit the appeal's name and goal.
I've also added tests to the appeal.
=> MPDX-7955 - Add edit appeal functionality

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx
In this PR, I added a warning message on the edit partnership modal that only shows when a contact is switched from the "Partner - Financial" status to another, and either the committed amount or committed frequency or both are filled out.
The user is presented with two options. Yes, clear the amount and frequency, or No, leave them as they are.
=> MPDX-8130 - Add Remove commitment warning on the Edit Partnership modal

src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/AddDonation/AddDonation.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/AddDonation/StyledComponents.tsx, src/components/Tool/Appeal/AppealsContext/contacts.graphql, src/components/Tool/Appeal/List/ContactRow/ContactRow.test.tsx, src/components/Tool/Appeal/List/ContactRow/ContactRow.tsx, src/components/Tool/Appeal/List/ContactRow/ContactRowMock.ts, src/components/Tool/Appeal/List/ContactsList/ContactsList.tsx, src/components/Tool/Appeal/Modals/DeleteAppealContact/DeleteAppealContact.graphql, src/components/Tool/Appeal/Modals/DeleteAppealContact/DeleteAppealContactModal.test.tsx, src/components/Tool/Appeal/Modals/DeleteAppealContact/DeleteAppealContactModal.tsx, src/components/Tool/Appeal/Modals/DeleteAppealContact/DynamicDeleteAppealContactModal.tsx, src/components/Tool/Appeal/Modals/DeletePledgeModal/DeletePledge.graphql, src/components/Tool/Appeal/Modals/DeletePledgeModal/DeletePledgeModal.test.tsx, src/components/Tool/Appeal/Modals/DeletePledgeModal/DeletePledgeModal.tsx, src/components/Tool/Appeal/Modals/DeletePledgeModal/DynamicDeletePledgeModal.tsx, src/components/Tool/Appeal/Modals/PledgeModal/ContactPledge.graphql, src/components/Tool/Appeal/Modals/PledgeModal/DynamicPledgeModal.tsx, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.test.tsx, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
In this PR, I added functionality to the contact row. Allow the user to add a pledge, edit a pledge, delete a pledge, remove a contact from an appeal and add an excluded contact.
You will see I added some files from the commit `[1. List Filters - Add contacts to appeal](https://github.com/CruGlobal/mpdx-react/commit/c2412ee8379da48151c5e0cdfc13e81d0862fd3c)` otherwise this PR would break.  This should be merged in before this merges so I will remove that once that happens.
- **Add a Pledge:** Implemented the ability to add a new pledge with associated donation amounts.
- **Edit a Pledge:** Enabled the editing of existing pledges within a contact row.
- **Delete a Pledge:** Added functionality to delete a pledge.
- **Remove Contact from Appeal:** Users can now remove a contact from an …
=> Appeal list contact row functionality

src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.test.tsx, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
In this PR, I fixed an issue which I created where when someone is editing a commitment in Appeals, they see the message "You are adding a commitment to {name}".
I've now made a different message show when the user is editing the commitment.
=> Making the Edit Commitment message different than the add commitment.

pages/setup/Account.graphql, pages/setup/account.page.test.tsx, pages/setup/account.page.tsx
* Add default account setup page to let the user choose their default account list
* If the user has only one account list, the server will set this account list to the default and redirect to the next step in the tour
[MPDX-8096](https://jira.cru.org/browse/MPDX-8096)
=> [MPDX-8096] Add default account setup page

pages/accountLists.page.test.tsx, pages/accountLists.page.tsx, pages/accountLists/[accountListId].page.test.tsx, pages/accountLists/[accountListId].page.tsx, pages/api/utils/pagePropsHelpers.test.ts, pages/api/utils/pagePropsHelpers.ts, pages/setup/account.page.tsx
Virtually every `getServerSideProps` method needs to first load the session, redirect to the login page if it is missing, then uses the session to run custom logic. This PR adds a helper method `makeGetServerSideProps` to reduce some of this boilerplate. Simply pass it a function that accepts a `session` and returns the page props. The helper function will load the session, pass it to the custom function you provided, and add the session to any page props returned.
Will be used in [MPDX-8084](https://jira.cru.org/browse/MPDX-8084) and [MPDX-8087](https://jira.cru.org/browse/MPDX-8087)
=> [MPDX-8094] Add makeGetServerSideProps helper to reduce boilerplate in `getServerSideProps`

README.md, next.config.js, pages/GetAccountLists.graphql, pages/_app.page.tsx, pages/accountLists.page.test.tsx, pages/accountLists.page.tsx, pages/accountLists/[accountListId]/settings/integrations/index.page.test.tsx, pages/accountLists/[accountListId]/settings/integrations/index.page.tsx, pages/accountLists/[accountListId]/settings/notifications.page.test.tsx, pages/accountLists/[accountListId]/settings/notifications.page.tsx, pages/accountLists/[accountListId]/settings/preferences.page.test.tsx, pages/accountLists/[accountListId]/settings/preferences.page.tsx, pages/setup/account.page.test.tsx, pages/setup/account.page.tsx, pages/setup/connect.page.tsx, pages/setup/start.page.test.tsx, pages/setup/start.page.tsx, src/components/AccountLists/AccountLists.stories.tsx, src/components/AccountLists/AccountLists.test.tsx, src/components/Setup/Connect.test.tsx, src/components/Setup/Connect.tsx, src/components/Setup/Setup.graphql, src/components/Setup/SetupProvider.test.tsx, src/components/Setup/SetupProvider.tsx, src/components/Setup/useNextSetupPage.test.tsx, src/components/Setup/useNextSetupPage.ts
* On the account's list page, do a server-side redirect to force the user to take the tour if their account isn't set up.
* On every page, do a client-side redirect to force the user to take the tour if their account isn't set up.
* Provide `settingUp` context to the entire application. It will be used in a future PR to hide navbar links when in setup mode.
[MPDX-8087](https://jira.cru.org/browse/MPDX-8087)
=> [MPDX-8087] Take the user through the tour if their account isn't set up

pages/accountLists/[accountListId]/tools/ToolsWrapper.tsx, pages/accountLists/[accountListId]/tools/appeals/appeal/[[...appealId]].page.test.tsx, pages/accountLists/[accountListId]/tools/appeals/appeal/[[...appealId]].page.tsx
In this PR, I edit the Tools wrapper to allow for the appeals page to be full width & height of the screen.
I haven't added this to the initial appeals page, as this is currently like the old MPDX.
=> Removing the limitations of the new Tools Wrapper menu on appeals.

pages/accountLists/[accountListId]/settings/integrations/index.page.test.tsx, pages/accountLists/[accountListId]/settings/integrations/index.page.tsx, pages/accountLists/[accountListId]/settings/notifications.page.test.tsx, pages/accountLists/[accountListId]/settings/notifications.page.tsx, pages/accountLists/[accountListId]/settings/preferences.page.test.tsx, pages/accountLists/[accountListId]/settings/preferences.page.tsx, src/components/Layouts/Primary/LogoLink/LogoLink.test.tsx, src/components/Layouts/Primary/LogoLink/LogoLink.tsx, src/components/Layouts/Primary/NavBar/NavBar.test.tsx, src/components/Layouts/Primary/NavBar/NavBar.tsx, src/components/Layouts/Primary/NavBar/NavTools/NavTools.test.tsx, src/components/Layouts/Primary/NavBar/NavTools/NavTools.tsx, src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.test.tsx, src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.tsx, src/components/Layouts/Primary/Primary.test.tsx, src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx, src/components/Layouts/Primary/TopBar/TopBar.test.tsx, src/components/Layouts/Primary/TopBar/TopBar.tsx, src/components/Setup/SetupProvider.test.tsx, src/components/Setup/SetupProvider.tsx, src/components/Shared/MultiPageLayout/MultiPageHeader.test.tsx, src/components/Shared/MultiPageLayout/MultiPageHeader.tsx
* Hide navbar links when the user is on the setup tour, while keeping things like the logo, Sign Out button, and username
* Hide the left panel that contains the settings links and hide the toggle button when on settings pages during the setup tour
* Various improvements to existing navbar tests
There isn't a specific Jira ticket for this, but it is related to tickets like [MPDX-8091](https://jira.cru.org/browse/MPDX-8091), [MPDX-8092](https://jira.cru.org/browse/MPDX-8092), [MPDX-8093](https://jira.cru.org/browse/MPDX-8093)
=> [MPDX-8091] Hide links in the navbar when the user is on the setup tour

src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.test.tsx, src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.tsx
In this PR, I fix the star filtering on the Flows view. I also added the "Add Contact to Appeal" button to the asked column. Refreshing the contacts queries once contacts are added.
=> MPDX-8154 Add Contact Button and fix Star filtering

src/components/Shared/Header/ListHeader.test.tsx, src/components/Shared/Header/ListHeader.tsx, src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx, src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.test.tsx, src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.tsx, src/hooks/useMassSelection.test.ts, src/hooks/useMassSelection.ts
In this pull request, I enabled users to select all and deselect all contacts within a specific column on the flows view. When selecting, contacts are added/removed from the list of previously selected contacts.
This functionality replicates how the old MPDX worked. I had to add 2 more functions to the useMassSelection hook to allow for multiple contact IDs to be passed through for checking or unchecking.
=> MPDX-8124 Adding select and deselect all functionality onto each column in the flows view

src/components/Contacts/ContactFlow/ContactFlowSetup/Header/ResetToDefault/ResetToDefaultModal.test.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Header/ResetToDefault/ResetToDefaultModal.tsx
Is this what we had in mind? I forgot that we already had a warning message. I made the warning it a little bit more explicit, but I'm definitely open to suggestions.
Before:
After:
[MPDX-8175](https://jira.cru.org/browse/MPDX-8175)
=> [MPDX-8175] Tweak reset flows warning message

src/components/Tool/Appeal/AppealsContext/contacts.graphql, src/components/Tool/Appeal/Flow/ContactFlowRow/ContactFlowRow.tsx, src/components/Tool/Appeal/List/ContactRow/ContactRow.tsx, src/components/Tool/Appeal/List/ContactRow/ContactRowMock.ts, src/components/Tool/Appeal/Shared/useGetPledgeOrDonation/useGetPledgeOrDonation.test.ts, src/components/Tool/Appeal/Shared/useGetPledgeOrDonation/useGetPledgeOrDonation.ts
Fix for showing multiple amounts for contacts on the Given column and showing $0 donated amount when the contact had donated an actual amount.
**1. Showing multiple amounts for contacts on the Given column**
After reviewing how the old MPDX renders the contact row, I saw I was doing it incorrectly. I was looping through the donations given and showing the pledge with the amount donated.
This was incorrect; it should show one pledge amount, with one total donated amount and the latest date donated.
**2. Showing the $0 donated amount when the contact donated an actual amount.**
This was caused by me using the wrong value `appealAmount` instead of `amount`.
=> MPDX-8082 - Given contact - show 1 pledge, total donated and last donated date

src/components/Tool/Appeal/Modals/AddContactToAppealModal/AddContactToAppealModal.test.tsx, src/components/Tool/Appeal/Modals/AddContactToAppealModal/AddContactToAppealModal.tsx, src/components/Tool/Appeal/Modals/AddContactToAppealModal/AppealContacts.graphql, src/components/Tool/Appeal/Modals/AddContactToAppealModal/AppealInfo.graphql, src/components/Tool/Appeal/Modals/AddExcludedContactModal/AddExcludedContactModal.test.tsx, src/components/Tool/Appeal/Modals/AddExcludedContactModal/AddExcludedContactModal.tsx
In this PR, I add a message to the add Contact modal to inform the user that they are adding excluded contacts.
In the old MPDX, they close the modal and open the add excluded modal, but since I allow multiple contacts to be added and I think it's better UX, I have added an info alert that shows when an excluded contact is selected.
I also list out the excluded contact names.
I have added tests for this new functionality.
This PR is related to task [MPDX-8181](https://jira.cru.org/browse/MPDX-8181) not 1880. My mistake.
=> MPDX-8181 - Showing excluded contacts message when adding contacts that are excluded

src/components/Task/Modal/Form/Inputs/ContactsAutocomplete/ContactsAutocomplete.test.tsx, src/components/Task/Modal/Form/Inputs/ContactsAutocomplete/ContactsAutocomplete.tsx, src/components/Task/Modal/TaskModal.tsx
When creating or editing a task on a hidden contact, the contact name wasn't showing in the contacts autocomplete because the query to load contacts only returns active contacts by default.
To test, add a task on a contact with the status "Never Ask" and verify that the contact name shows up.
Before:
After:
This is likely the issue that Keely experienced during task phases UAT.
I'm basing this PR on `main` because it is present in production and can be fixed without depending on task phases.
https://jira.cru.org/browse/MPDX-8174
https://jira.cru.org/browse/MPDX-8097 (same ticket reported earlier by me)
=> [MPDX-8174] Missing contact name on hidden contact

src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.test.tsx, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.tsx, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealFormMocks.ts, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.test.tsx, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
In this PR, I will make the edit Pledge model more like the old MPDX. 
**When the pledge has a status of `given`:**
- The amount should be disabled and not editable.
- The status should be `Given`, but this shouldn't show as an option to select.
**When the pledge has a status of `Received`:**
- It should show the received status, but otherwise, it should be hidden.
_This is unlike the old MPDX, the old MPDX shows the received status as a option, but when users select it, the contact/pledge stays in committed and causes a lot of confusion._
We have thought about removing the received column entirely, that is a large change. This might help with some of the confusion.
=> MPDX-8183 Simplifying the UX of the Pledge modal when status given or received

src/components/Tool/Appeal/AppealDetails/AppealHeaderInfo/AppealHeaderInfo.test.tsx, src/components/Tool/Appeal/AppealDetails/AppealHeaderInfo/AppealHeaderInfo.tsx
Appeal header was rendering a loading skeleton instead of $0 when the goal amount was 0.
[MPDX-8190](https://jira.cru.org/browse/MPDX-8190)
=> [MPDX-8190] Render 0 instead of loading when goal is 0

src/components/Tool/Appeal/AppealsContext/AppealsContext.test.tsx, src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx
In the appeals list view if you switch off of the Asked list to another list, like Given, then reload the page, you were taken back to the Asked list. This PR preserves the list that the user was on and only takes them to Asked if they didn't have `appealStatus` set in the filters in the URL.
[MPDX-8186](https://jira.cru.org/browse/MPDX-8186)
=> [MPDX-8186] Preserve the appeals list the user was viewing

src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.test.tsx, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.tsx
Require the admin percentage to be a whole number.
[MPDX-8192](https://jira.cru.org/browse/MPDX-8192)
=> [MPDX-8192] Do not allow fractional admin percentages

src/components/Tool/FixSendNewsletter/Contact.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8207&sprint=1259#
=> MPDX-8207 fixSendNewsletter stop hiding content

src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.test.tsx, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.tsx, src/components/Tool/Appeal/InitialPage/AppealsInitialPage.tsx
* Initially set `Add contacts with the following status(es):` to `-- All Active --`
* Initially set `Do not add contacts who:` to `Have "Send Appeals" set to No`
=> [MPDX-8193] Preselect new appeal options

src/components/Contacts/ContactPartnershipStatus/ContactPartnershipStatus.test.tsx, src/components/Contacts/ContactPartnershipStatus/ContactPartnershipStatus.tsx
In this PR, I stop the component ContactPartnershipStatus from rendering 0 when the pledge amount has been set to 0.
=> MPDX-8225 - Prevent ContactPartnershipStatus.tsx from rendering "0" when pledge amount is 0

pages/api/graphql-rest.page.ts, src/components/Reports/FourteenMonthReports/Layout/Table/Table.test.tsx, src/components/Reports/FourteenMonthReports/Layout/Table/Table.tsx, src/components/Reports/FourteenMonthReports/Layout/Table/TableHead/TableHead.tsx
One major discrepancy I saw is that the 14 month reports were actually including 15 months. I adjusted the date range in the query to match Angular.
@wrandall22 Do you want to test again in preview that this fixes the discrepancies you were seeing? The numbers match on my account now, besides rounding differences (React is more accurate).
[MPDX-8221](https://jira.cru.org/browse/MPDX-8221) and [MPDX-8228](https://jira.cru.org/browse/MPDX-8228)
=> [MPDX-8221] Align 14 month reports with Angular

src/components/Layouts/Primary/NavBar/NavItem/NavItem.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx, src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/Item/Item.tsx
In this PR, Nav and menu links that link to a new page can now be opened in a new tab as the browser sees them as actual links.
The header nav was JS links and not `<a/>` tags, preventing users from opening the page in a new tab.
=> MPDX-8218 - Open Nav and menu links in new tab

src/components/DonationTable/DonationTable.graphql, src/components/DonationTable/DonationTable.test.tsx, src/components/DonationTable/DonationTable.tsx, src/components/EditDonationModal/EditDonationModal.graphql, src/components/EditDonationModal/EditDonationModal.test.tsx, src/components/EditDonationModal/EditDonationModal.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenu.test.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenu.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8220&sprint=1259#
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8222&sprint=1259#
- Check if designation name doesn't exist, then use the designationNumber
=> MPDX-8220 Donation Designation

__tests__/util/setup.ts, src/components/Reports/FourteenMonthReports/Layout/Header/Actions/Actions.test.tsx, src/components/Reports/FourteenMonthReports/Layout/Header/Actions/Actions.tsx
Sometimes the fourteen month report export button was doing nothing. This is because only part of the button was a download link. Now, the entire button is a download link. The easiest way to accomplish this was to stop using the react-csv `Link` component and instead use the method that it uses internally to create the blob download URL and add that `href` to the `Button` component.
@wrandall22 If you have time, let me know if you can reproduce the bug after this fix.
[MPDX-8230](https://jira.cru.org/browse/MPDX-8230)
=> [MPDX-8230] Fix 14 month report export button doing nothing

pages/_app.page.tsx, src/lib/apollo/client.ts
Import router in client.ts so router.replace from _app.page doesn't interfere with the replace in contacts context.
=> [No Jira] Import router in client.ts

pages/api/Schema/reports/fourteenMonth/datahandler.ts
In production, the 14 month partner reports were giving GraphQL errors like `Enum "StatusEnum" cannot represent value: "PARTNER - FINANCIAL"`. That is because in production, partner statuses are still strings like "Partner - Financial" (not "partner_financial") until the task phases API changes merge into production.
To test that this change fixes the issue, run `REST_API_URL=https://api.mpdx.org/api/v2/ yarn start` on `main` (to temporarily point the REST API at production) and go to a 14 month report page to see the issue. Then run `REST_API_URL=https://api.mpdx.org/api/v2/ yarn start` on this branch and go to a 14 month report to see the issue resolved.
Follow up to #1080
[MPDX-8221](https://jira.cru.org/browse/MPDX-8221)
=> [MPDX-8221] Convert contact statuses correctly

src/components/Tool/FixCommitmentInfo/Contact.test.tsx, src/components/Tool/FixCommitmentInfo/Contact.tsx, src/components/Tool/FixCommitmentInfo/FixCommitmentInfo.test.tsx, src/components/Tool/FixCommitmentInfo/FixCommitmentInfo.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8264&sprint=1268#
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8265&sprint=1268#
- Suggested statuses have data like partner_financial and Partner - Financial so we need to convert that to the StatusEnum before passing it to the Select.
- Suggested frequencies are in number format like 1 instead of 'Monthly'. I convert these to enums.
- Fix tests with these changes
- Small styling changes for small screens
=> MPDX-8264 Fix status and frequency

src/components/Task/Modal/Form/Inputs/SuggestedContactStatus/SuggestedContactStatus.test.tsx, src/components/Task/Modal/Form/Inputs/SuggestedContactStatus/SuggestedContactStatus.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8263&sprint=1268#
-Change logic so the suggested contact status shows when a contact has no status
-Add test
=> MPDX-8263 Suggested Contact Show

src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.graphql, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.test.tsx, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.tsx, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealFormMocks.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8257&sprint=1268#
- Replace hard coded and graphql contact statuses with ones from useContactPartnershipStatuses() hook
- Fix tests
=> MPDX-8257 Create-appeal-contacts

.github/workflows/ci.yml, lighthouse/lighthouse-origin.js
In this PR, I update the GitHub Actions to use the new domains
=> MPDX-8274 Pointing GH CI to use new domain after we switch react MPDX to production

pages/accountLists/[accountListId]/contacts/flows/setup.page.tsx, src/components/Contacts/ContactFlow/ContactFlow.tsx, src/components/Contacts/ContactFlow/ContactFlowColumn/ContactFlowColumn.test.tsx, src/components/Contacts/ContactFlow/ContactFlowColumn/ContactFlowColumn.tsx, src/components/Contacts/ContactFlow/ContactFlowDragLayer/ContactFlowDragLayer.tsx, src/components/Contacts/ContactFlow/ContactFlowDragLayer/ContactFlowRowPreview.tsx, src/components/Contacts/ContactFlow/ContactFlowDropZone/ContactFlowDropZone.tsx, src/components/Contacts/ContactFlow/ContactFlowRow/ContactFlowRow.test.tsx, src/components/Contacts/ContactFlow/ContactFlowRow/ContactFlowRow.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Column/ContactFlowSetupColumn.test.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Column/ContactFlowSetupColumn.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Column/UnusedStatusesColumn.test.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Column/UnusedStatusesColumn.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/DragLayer/ContactFlowSetupDragLayer.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/DragPreview/ContactFlowSetupDragPreviewStatus.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/DropZone/ContactFlowSetupDropZone.test.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/DropZone/ContactFlowSetupDropZone.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Header/ContactFlowSetupHeader.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Row/ContactFlowSetupStatusRow.test.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Row/ContactFlowSetupStatusRow.tsx, src/components/Contacts/ContactFlow/contactFlowDefaultOptions.ts, src/components/Contacts/ContactFlow/useFlowOptions.test.tsx, src/components/Contacts/ContactFlow/useFlowOptions.ts, src/hooks/useContactPartnershipStatuses.ts, src/hooks/usePhaseData.ts
Fix contact flows bugs. The root cause was that the flows options columns were names like "Partner - Financial", which doesn't match any statuses. I'm changing the options to use UPPERCASE_UNDERSCORE statuses, namely the values of `StatusEnum`.
The first 7 commits (`Remove unneeded TypeScript ref prop hack` through `Add argument type to setPhaseId`) are just cleanup commits and are not core to the changes in this PR.
[MPDX-8256](https://jira.cru.org/browse/MPDX-8256), [MPDX-8255](https://jira.cru.org/browse/MPDX-8255), [MPDX-8259](https://jira.cru.org/browse/MPDX-8259)
=> [MPDX-8256, MPDX-8255, MPDX-8259] Fix contact flows bugs

src/components/Contacts/ContactRow/ContactRow.tsx, src/components/Shared/Filters/FilterListItem.test.tsx, src/components/Shared/Filters/FilterListItemMultiselect.tsx, src/components/Shared/Filters/MultiselectFilterAutocomplete.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8306&sprint=1268#
- Group statuses by phase in filters
=> MPDX-8306 Add phase grouping of statuses

src/components/Reports/EmptyReport/EmptyReport.stories.tsx, src/components/Reports/FourteenMonthReports/FourteenMonthReport.tsx, src/components/Reports/ResponsibilityCentersReport/ResponsibilityCentersReport.tsx
- Add message telling users that Responsibility Centers is not working.
=> Add RC message

pages/login-apioauth.page.test.tsx, pages/login.page.test.tsx, pages/login.page.tsx, src/components/Welcome/Welcome.tsx
* Add instructions for creating an Okta account to the login page. This text is hidden when the auth provider is API Oauth.
* ~~Refactor some login page tests for improved isolation.~~
[MPDX-8086](https://jira.cru.org/browse/MPDX-8086)
=> [MPDX-8086] Add account creation instructions to login page

pages/accountLists/[accountListId]/setup/finish.page.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/UpdateUserOptions.graphql
* After setting `setup_position` to `''` to end the tour, the new value wasn't being updated in the Apollo cache, and the tour banner was still being shown. This change reloads the `setup_position` after saving the new value.
* Also localize a couple of labels.
Completes part of [MPDX-8204](https://jira.cru.org/browse/MPDX-8204)
=> [MPDX-8204] Refresh setup position

README.md, next.config.js, pages/accountLists.page.test.tsx, pages/accountLists.page.tsx, src/components/Setup/SetupProvider.test.tsx, src/components/Setup/SetupProvider.tsx
* Instead of showing the setup tour on multiple preferences pages if the user was in the middle of a tour, only show the setup tour if their current page matches their setup_position option.
* Also, remove the `DISABLE_SETUP_TOUR` feature flag now that tools is live.
[MPDX-8204](https://jira.cru.org/browse/MPDX-8204)
=> [MPDX-8204] Only show the setup tour if setup_position matches the current page

src/components/Dashboard/ThisWeek/TasksDueThisWeek/TasksDueThisWeek.test.tsx, src/components/Dashboard/ThisWeek/TasksDueThisWeek/TasksDueThisWeek.tsx
https://jira.cru.org/browse/MPDX-8335
Currently the Tasks Due this week is not showing the task action. Only the task title.
- Add the correct task action name which includes the phase.
=> MPDX-8335 Task Due This Week

pages/api/Schema/Settings/Integrations/Google/createGoogleIntegration/datahandler.ts, pages/api/Schema/Settings/Integrations/Google/googleAccountIntegrations/datahandler.ts, pages/api/Schema/Settings/Integrations/Google/googleAccountIntegrations/googleAccountIntegrations.graphql, pages/api/Schema/Settings/Integrations/Google/parse.ts, pages/api/Schema/Settings/Integrations/Google/updateGoogleIntegration/datahandler.ts, pages/api/graphql-rest.page.ts, src/components/Settings/integrations/Google/Modals/EditGoogleAccountModal.test.tsx, src/components/Settings/integrations/Google/Modals/EditGoogleIntegrationForm.tsx, src/components/Settings/integrations/Google/Modals/googleIntegrations.graphql
The Google Calendar integration activity type checkboxes were using the translated names. This PR switches them to use `ActivityTypeEnum` values. This PR also contains some general cleanup and improvements to `EditGoogleIntegrationForm`.
[MPDX-8330](https://jira.cru.org/browse/MPDX-8330)
=> [MPDX-8330] Fix Google Calendar integration activity type checkboxes

src/components/Coaching/CoachingDetail/Activity/Activity.test.tsx, src/components/Coaching/CoachingDetail/Activity/Activity.tsx
* Remove `status === null` filter from the Connections Remaining link on the coaching report page.
* Fix tests that will fail if you have HELP_URL_* environment variables set locally.
To test, go to Reports > Coaching, then click on the Connections Remaining link. Verify that the number on the coaching report matches the number of contacts showing on the contacts page. Before, too many contacts were showing because it was including contacts with a null status.
[MPDX-8341](https://jira.cru.org/browse/MPDX-8341)
=> [MPDX-8341] Fix coaching Connections Remaining link filter

pages/accountLists/[accountListId]/contacts/ContactsWrapper.tsx, pages/accountLists/[accountListId]/tasks/[[...contactId]].page.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.tsx, src/components/Dashboard/Welcome/Welcome.tsx, src/components/Shared/Header/ListHeader.test.tsx, src/components/Shared/Header/ListHeader.tsx, src/components/common/SearchBox/SearchBox.tsx
https://secure.helpscout.net/conversation/2726128388/1238886?folderId=7669074
- Show tooltip so users know what they can search for
- Automatically show the filters on Contacts and Tasks
- Fix amperstand on welcome message
=> HelpScout Tasks Search

src/components/Task/Modal/Form/Complete/TaskModalCompleteForm.test.tsx, src/components/Task/Modal/Form/Inputs/SuggestedContactStatus/SuggestedContactStatus.graphql, src/components/Task/Modal/Form/Inputs/SuggestedContactStatus/SuggestedContactStatus.test.tsx, src/components/Task/Modal/Form/Inputs/SuggestedContactStatus/SuggestedContactStatus.tsx, src/hooks/useContactPartnershipStatuses.ts
* Much of the flakiness seems to be that the contact status wasn't being mocked correctly. If the contact status was in the partner care phase, the suggested status checkbox would be hidden.
* I also memoized `contactStatuses` since it was used in a dependency array in `SuggestedContactStatus`.
[MPDX-8363](https://jira.cru.org/browse/MPDX-8363)
=> [MPDX-8363] Fix flaky suggested contact status tests

src/components/Dashboard/ThisWeek/GetThisWeek.graphql, src/components/Dashboard/ThisWeek/LateCommitments/LateCommitments.test.tsx, src/components/Dashboard/ThisWeek/LateCommitments/LateCommitments.tsx, src/components/Dashboard/ThisWeek/ThisWeek.mock.ts, src/components/Dashboard/ThisWeek/ThisWeek.tsx
https://secure.helpscout.net/mailbox/2c1fe7d687998a44/7669074/
https://secure.helpscout.net/conversation/2725829190/1238582?folderId=7669074
Issue: 
Right now the API returns the first 3 late commitments (anything that is even 1 day late). Then the FE hides late commitments that are less than 7 days late. So sometimes those 3 late commitments get filtered out and it shows that there are no late commitments.
Fix:
- Remove front-end filtering
- Make the API only get commitments that are at least 30 days late. (This is how angular did it)
=> Fix Late Commitments

src/components/Coaching/CoachingDetail/Activity/Activity.test.tsx, src/components/Coaching/CoachingDetail/Activity/Activity.tsx, src/components/Coaching/CoachingDetail/helpers.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8365&sprint=1276#
- Format dates correctly
- subtract one day from start date on Activity so it starts on sunday
=> MPDX-8365 Coaching-dates

pages/_document.page.tsx
Add a link to the HelpJuice ticket tracking the `DOMContentLoaded` bug. If it gets resolved in the future, we can switch to loading the beacon with a Next.js `<Script>`, which will be better for performance.
=> [no-Jira] Add link to HelpJuice ticket

src/components/Coaching/CoachingDetail/OutstandingNeeds/OutstandingNeeds.graphql, src/components/Coaching/CoachingDetail/OutstandingNeeds/OutstandingNeeds.test.tsx, src/components/Coaching/CoachingDetail/OutstandingNeeds/OutstandingNeeds.tsx, src/lib/apollo/cache.ts
Angular and React were showing different numbers of outstanding special needs. This is because React was showing all pledges on the primary appeal, but Angular was showing not received pledges from any appeal. They are now consistent again.
Note that in both REST and GraphQL, coaches cannot filter pledges by status. See this method that ignores all filters besides `contact_id` for coaches: https://github.com/CruGlobal/mpdx_api/blob/f6b0395b143a8dc104ba016eae26b832ad3a8995/app/controllers/api/v2/account_lists/pledges_controller.rb#L97-L105
[MPDX-8350](https://jira.cru.org/browse/MPDX-8350)
=> [MPDX-8350] Fix missing outstanding special needs

pages/api/Schema/reports/pledgeHistories/dataHandler.ts, pages/api/Schema/reports/pledgeHistories/pledgeHistories.graphql, pages/api/Schema/reports/pledgeHistories/resolvers.ts, pages/api/graphql-rest.page.ts, src/components/Coaching/CoachingDetail/Activity/Activity.test.tsx, src/components/Coaching/CoachingDetail/Activity/Activity.tsx, src/components/Coaching/CoachingDetail/CoachingDetail.tsx, src/components/Coaching/CoachingDetail/CoachingLink.test.tsx, src/components/Coaching/CoachingDetail/CoachingLink.tsx, src/components/Coaching/CoachingDetail/MonthlyCommitment/MonthlyCommitment.graphql, src/components/Coaching/CoachingDetail/MonthlyCommitment/MonthlyCommitment.stories.tsx, src/components/Coaching/CoachingDetail/MonthlyCommitment/MonthlyCommitment.test.tsx, src/components/Coaching/CoachingDetail/MonthlyCommitment/MonthlyCommitment.tsx, src/components/Coaching/CoachingDetail/MonthlyCommitment/helpers.test.ts, src/components/Coaching/CoachingDetail/MonthlyCommitment/helpers.ts, src/components/Coaching/CoachingDetail/MonthlyCommitment/useMonthlyCommitmentAverage.test.tsx, src/components/Coaching/CoachingDetail/MonthlyCommitment/useMonthlyCommitmentAverage.ts
The previous monthly commitment average and goal was inaccurate compared to Angular. This PR adds the correct method for calculating the average and goal. It also moves the complex logic into helper functions and hooks.
[MPDX-8349](https://jira.cru.org/browse/MPDX-8349)
=> [MPDX-8349] Add monthly commitment average and goal

src/components/Contacts/ContactsMap/ContactsMap.tsx
In this PR, I change the z-index of the Google map so it appears below the site's navigation and still above the HelpDuck's beacon, as that has a z-index of `2147483647` 😂
=> MPDX-8362 - Move Google map under navigation

pages/accountLists/[accountListId]/settings/preferences.page.test.tsx, pages/accountLists/[accountListId]/settings/preferences.page.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8380&sprint=1276#
- Add redirect to preferences page
=> MPDX-8380 Data Export Redirect

pages/print.css
I hide the Help Juice beacon as it blocks content when user's print out reports.
This was added to the old BEason, but looks like it was removed in the migration to Help Juice. - https://github.com/CruGlobal/mpdx-react/pull/1019/files#diff-e98282886594b0fe4dec5aac96decb88fe7efba8d4b06283027b6a1be41c3c0a
=> Print - Remove help juice beacon to not block content on page.

src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx, src/components/Settings/Admin/ImpersonateUser/ImpersonateUserAccordion.tsx, src/components/Settings/Organization/ImpersonateUser/ImpersonateUserAccordion.tsx
* The old message had "MPDX" hardcoded and was inaccurate since we don't redirect to the legacy MPDX anymore.
* The impersonation page tells you to click the "Exit Impersonation Mode" button but the button is actually called "Stop Impersonating".
=> [no-Jira] Improve impersonation labels

src/components/Contacts/ContactDetails/ContactDetailsTab/PartnerAccounts/ContactPartnerAccounts.graphql, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/AddDonation/AddDonation.test.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/AddDonation/AddDonation.tsx
In the Add Donation modal when there is only one designation account, preselect it.
https://secure.helpscout.net/conversation/2734816905/1243276?viewId=320673
=> [HS-1243276] Prepopulate donation designation account with only option

src/components/Contacts/MassActions/Exports/Emails/GetEmailsForExporting.graphql, src/components/Contacts/MassActions/Exports/Emails/MassActionsExportEmailsModal.test.tsx, src/components/Contacts/MassActions/Exports/Emails/MassActionsExportEmailsModal.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmailMocks.ts, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/GetNewsletterContacts.graphql
A user pointed out that we aren't exporting all the people's emails under each contact when exporting the newsletter email list on the dashboard.
Upon investigating, Scott Michell found that in addition to the above, when you export emails using the bulk action, it includes all the people's emails even if they have opted out.
HelpScout: https://secure.helpscout.net/conversation/2740763718/1246535/
Jira: https://jira.cru.org/browse/MPDX-8403
1.  On the export email bulk action on the contacts page, we only include people's email addresses who have not opted out of the digital newsletter.
2. The e-mail Newsletter list now pulls all the people under each contact, as long as they haven't asked to be opted out of the digital newsletter.
=> MPDX 8403 - Fix email exports to export the correct emails

src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskCommentsButton/TaskCommentsButton.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskCompleteButton/TaskCompleteButton.tsx
Fix the `data-testid` prop to avoid `React does not recognize the data-testId prop on a DOM element` warnings in DevTools.
FYI @caleballdrin
=> [no-Jira] Fix data-testid prop spelling

pages/_app.page.tsx, pages/helpjuice.css, src/components/Helpjuice/DismissableBeacon.test.tsx, src/components/Helpjuice/DismissableBeacon.tsx, src/components/Helpjuice/Helpjuice.test.tsx, src/components/Helpjuice/Helpjuice.tsx, src/components/Helpjuice/widget.mock.ts
Make the Helpjuice beacon dismissable. There is a new Hide Beacon link in the beacon widget that dismisses the beacon. Once dismissed, the beacon peeks just barely out from the right side of the screen. Hovering over it causes it to slide out, and clicking on it makes it no longer dismissed.
On most pages, the dismissed preference is saved to a persistent user preference. On login and error pages, we don't have an Apollo client, so the preference can't be persisted, but the beacon can still be temporarily dismissed until the next page load.
I had to jump through some hoops to get this to work, but the complexity is abstracted away into the `Helpjuice` component, and the comments for `ApolloBeacon` and `NoApolloBeacon` should describe what is going on. I chose not to do something like this …
=> [MPDX-8393] Make the Helpjuice beacon dismissable

src/components/Shared/Filters/FilterListItemMultiselect.tsx
Fix MUI warning:
```
You are providing a disabled button child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.
```
I went with the simple fix, but I could see a case for hiding the reverse button entirely instead of disabling it to reduce some clutter. This could be good since there are already so many different elements in the filter panel. Let me know your thoughts.
=> [no-Jira] Fix disabled tooltip button warning

pages/accountLists/[accountListId]/tasks/Tasks.test.tsx, pages/accountLists/[accountListId]/tasks/[[...contactId]].page.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.tsx, src/components/Contacts/ContactsContext/ContactsContext.tsx, src/components/Reports/PartnerGivingAnalysisReport/PartnerGivingAnalysisReport.tsx, src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx, src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.tsx, src/hooks/GetIdsForMassSelection.graphql, src/hooks/useMassSelection.test.ts, src/hooks/useMassSelection.ts, src/hooks/useUpdateTasksQueries.ts
When the list of contacts, tasks, or other entities changes, deselect any that were removed from the list.
* Go to the tasks page and select 2 tasks. You should see "2 Selected" in the header.
* Change the tasks filters so that only one of the selected tasks is visible. You should see "1 Selected" in the header.
[MPDX-8240](https://jira.cru.org/browse/MPDX-8240)
=> [MPDX-8240] Deselect removed ids

src/components/Tool/Appeal/List/ContactRow/ContactRow.test.tsx, src/components/Tool/Appeal/List/ContactRow/ContactRow.tsx
HelpScout Ticket: [1248886](https://secure.helpscout.net/conversation/2744971387/1248886?folderId=7296147)
Jira: [MPDX-8413](https://jira.cru.org/browse/MPDX-8413)
Fix the appeal contact row click to prevent it from opening contact when clicking on action icons.
=> MPDX-8413 - Appeal contact row actions click fix

src/components/Dashboard/Welcome/Welcome.tsx
https://jira.cru.org/browse/MPDX-7900
- remove header image and empty space
=> MPDX-7900 Remove Header image and make smaller

pages/accountLists/[accountListId]/reports/expectedMonthlyTotal/[[...contactId]].page.test.tsx, pages/accountLists/[accountListId]/reports/expectedMonthlyTotal/[[...contactId]].page.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Table/ExpectedMonthlyTotalReportTable.test.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Table/ExpectedMonthlyTotalReportTable.tsx
Add a contact right panel to the expected monthly total report so that clicking on a contact opens it there instead of going to the contacts list.
[MPDX-8406](https://jira.cru.org/browse/MPDX-8406)
=> [MPDX-8406] Add contact panel to expected monthly total report

src/components/Reports/FourteenMonthReports/Layout/Table/Table.test.tsx, src/components/Reports/FourteenMonthReports/Layout/Table/Table.tsx
https://jira.cru.org/browse/MPDX-8421
- Add colored circle if the partner is late on their giving. 
- Hide it on print view
=> MPDX-8421 14month Late Circle

pages/accountLists.page.test.tsx, pages/accountLists/[accountListId].page.test.tsx, pages/account_lists/[accountListId]/accept_invite/[inviteId].page.test.tsx, pages/account_lists/[accountListId]/accept_invite/[inviteId].page.tsx, pages/api/utils/pagePropsHelpers.test.ts, pages/api/utils/pagePropsHelpers.ts, pages/index.page.tsx, pages/login.page.tsx, pages/organizations/[orgId]/accept_invite/[inviteId].page.test.tsx, pages/organizations/[orgId]/accept_invite/[inviteId].page.tsx, pages/setup/account.page.test.tsx, src/components/RouterGuard/RouterGuard.tsx, src/components/Settings/Admin/ImpersonateUser/ImpersonateUserAccordion.tsx, src/components/Settings/Organization/ImpersonateUser/ImpersonateUserAccordion.tsx, src/lib/apollo/client.ts
Redirect the user back to the page they were trying to go to after they successfully log in.
Looking at the redirect trace in the DevTools network tab (select preserve log, filter by Doc to see page loads, and look at the `Location` response header), it appears that after sign in, NextAuth, redirects back to the page that initiated the login, in our case, `/login?redirect=xxx`. Our `getServerSideProps` function on the login page notices that we have a session and a redirect URL and redirects the user one last time to their original page.
* Go to a page that isn't a dashboard page (for example, tasks).
* Copy the URL.
* Sign out of MPDX and Okta.
* Navigate to the URL you copied.
* Ensure that when it takes you to the login page, `?redirect` is set to the tasks page.
* Ensure that you are …
=> [MPDX-8386] Redirect after login

src/components/Task/Modal/Form/Complete/TaskModalCompleteForm.test.tsx, src/components/Task/Modal/Form/Complete/TaskModalCompleteForm.tsx, src/components/Task/Modal/Form/LogForm/TaskModalLogForm.test.tsx, src/components/Task/Modal/Form/LogForm/TaskModalLogForm.tsx, src/components/Task/Modal/Form/TaskModalForm.test.tsx, src/components/Task/Modal/Form/TaskModalForm.tsx, src/components/Task/Modal/Form/TaskModalHelper.ts, src/hooks/usePhaseData.ts
* When creating a new task after completing a different task, default the task name to the previous task name.
* If the user changes the new task's task phase or activity type, the task name will be overridden, which I believe is what we want.
* ~~If the user had a customized task name for a text message task, for example, and they make the next action a phone call, we just use the autogenerated task name. This is to prevent someone who didn't customize their task name from getting "Call to Initiate Appointment" as the initial task name for a text message task. I think this is a reasonable tradeoff, but feel free to discuss.~~ **EDIT**: Now I'm just comparing the task subject with the default task subject. If they differ, this means that the user customized the task subject. This logic …
=> [MDPX-8385] Preserve previous task name

src/components/Reports/FinancialAccountsReport/AccountTransactions/AccountTransactions.test.tsx, src/components/Reports/FinancialAccountsReport/AccountTransactions/AccountTransactions.tsx, src/components/Reports/FourteenMonthReports/Layout/Header/Actions/Actions.test.tsx, src/components/Reports/FourteenMonthReports/Layout/Header/Actions/Actions.tsx
Excel does not interpret UTF-8 encoded CSV files correctly. For example, exports contain characters like this instead of Russian characters: `"–ï–¥–∞/–ø–æ–¥–∞—Ä–∫–∏ –¥–ª—è –≤—Å—Ç—Ä–µ—á
–£–∂–∏–Ω –° –∫–æ–º–∞–Ω–¥–æ–π –∏ —Å —Å—Ç—É–¥–µ–Ω—Ç–∞–º–∏"`. To fix this, we need to add the [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) to hint to Excel that it needs to interpret the file as UTF-8 instead of as ASCII. Fortunately, `react-csv` has an option for this. We just have to pass `true` as the second argument to `buildURI`.
I also migrated the account transactions CSV download from a handrolled CSV export to use `react-csv`.
Note that the API already adds the byte order mark to server-generated CSV exports.
* 14 Month Reports
* Create or edit a contact to have a non-ASCII …
=> [MPDX-8418] Add UTF-8 BOM to CSV exports

src/components/Contacts/ContactDetails/ContactDetailsTab/Tags/ContactTags.tsx, src/components/Contacts/MassActions/AddTags/MassActionsAddTagsModal.tsx, src/components/Shared/Filters/FilterPanel.tsx, src/components/Shared/Filters/TagsSection/FilterTagDeleteModal.tsx
* Sort tags in the filters panel alphabetically, like Angular did.
* Refresh the contact filters when contact tags are added or deleted.
* In the future, we should do something similar for task tags.
https://secure.helpscout.net/conversation/2749833892/1251563/
=> [HS-1251563] Sort and refresh contact tags

src/components/Shared/MassActions/TasksMassActionsDropdown.test.tsx, src/components/Task/MassActions/EditTasks/MassActionsEditTasksModal.test.tsx, src/components/Task/MassActions/EditTasks/MassActionsEditTasksModal.tsx, src/components/Task/Modal/Form/Inputs/ActivityTypeAutocomplete/ActivityTypeAutocomplete.tsx, src/components/Task/Modal/Form/Inputs/ActivityTypeAutocomplete/AssigneeAutocomplete/AssigneeAutocomplete.tsx, src/utils/functions/getLocalizedResultStrings.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8425&sprint=1282#
- Require Task Action on mass edit modal
=> MPDX-8425 Require Task Action on Mass Actions

pages/helpjuice.css, src/components/Helpjuice/Helpjuice.test.tsx, src/components/Helpjuice/Helpjuice.tsx, src/components/Helpjuice/widget.mock.ts
In the Helpjuice beacon, make the article header a link that opens the article in a new tab on Helpjuice.
* Search for an article and click on it or click on a suggested article
* Verify that the article header is a link that opens the article in a new tab
[MPDX-8416](https://jira.cru.org/browse/MPDX-8416)
=> [MPDX-8416] Turn article name into a link that opens in a new tab

.github/renovate.json, dependabot.yml
Use a dash in dependabot branch names. This will make preview environments work on dependabot PRs because the default / separator isn't a valid character in a domain name.
[Docs link](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pull-request-branch-nameseparator)
=> [no-Jira] Use a dash in dependabot branch names

src/lib/apollo/cache.ts
https://secure.helpscout.net/conversation/2761477377/1258682?folderId=7669074
Users with over 50 appeals were not able to see their appeals because Apollo was not merging the results from `useFetchAllPages` back into the result from the initial query.
Fix: Set the field policy of the field `appeals` to `paginationFieldPolicy`
=> HS-1258682 Appeals Loading Fix

src/components/Tool/Appeal/InitialPage/Appeals.tsx
Ensure React keeps track of the appeals, to ensure they are removed correctly when the user switches account.
=> Appeals - Remove appeals when switch account list

src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.tsx, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.test.tsx, src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
A lot of users have complained about the Received column and how it is confusing. In this PR, I'm adding a warning message that informs users not to select the Received status and adding a tooltip to the Received flows column title.
Helpscout: https://secure.helpscout.net/conversation/2764260250/1260229?folderId=7296147
**Test:**
1. Create an appeal and assign contacts to it.
2. Create a pledge; when you set the status to "Received", the warnings will show.
3. Edit a pledge which is "Committed", then set the status to "Received". This will show the warnings.
4. Edit a pledge which is "Received". the warnings will not show.
=> Appeals - Add warning and tooltip to Received title and pledge status dropdown

src/components/Task/Modal/TaskModalTask.graphql
Tasks on the contact no longer get reordered/removed when you click on a task comment.
The issue was reported, by multiple people. It happens when you are on a contact page and you have a lot of tasks, so not all of them are loaded on the initial load.
To test, follow the steps I lay out here in [this Jira ticket](https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8453#) on staging, and then on the preview deployment to see the fix.
Jira: [MPDX-8453](https://jira.cru.org/browse/MPDX-8453)
Helpscout: https://secure.helpscout.net/conversation/2751620240/1252918?folderId=7296147
=> [MPDX-8453] Tasks infinite scroll no longer scrolls to bottom on opening Comments modal

.github/workflows/ci.yml
Currently, Dependabot PRs fail in the `bundle-analzyer` step because the default GitHub token doesn't have permission to create a comment on the PR ([example run](https://github.com/CruGlobal/mpdx-react/actions/runs/11895982183/job/33146819121?pr=1200)). It appears that the fix is to give additional permissions to that workflow step ([docs](https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/)).
=> [no-Jira] Give bundle-analyzer permission to comment on dependabot PRs

.github/workflows/ci.yml, .github/workflows/onesky.yml, amplify.yml, src/components/Tool/Appeal/InitialPage/AddAppealForm/AddAppealForm.test.tsx
* On every commit to main run `yarn extract` before uploading labels to OneSky. That way translation can begin immediately on any new labels instead of needing to wait for `public/locales/en/translation.json` to be updated. (The extracted labels are not committed and are discarded when the action terminates)
* During deployment to Amplify, run `yarn onesky:download` to deploy the app with the latest labels from OneSky. I tested that if that command fails for any reason, the deployment will still continue successfully.
* I added the `ONESKY_*` environment variables to Amplify.
* Add a new workflow that runs daily to create a PR with any new labels from `yarn extract` or `yarn onesky:download`. Here is an example from my fork of the PR that will be created: …
=> [MPDX-8446] Automate translation download and extraction

src/components/Settings/integrations/Google/GoogleAccordion.tsx
#1204 accidentally removed some whitespace from the labels in `GoogleAccordion`. You can see in #1214 that those labels are changing, which will require them to be translated again for no reason. This PR reverts the change to the whitespace.
=> [no-Jira] Revert whitespace removed from GoogleAccordion labels

src/components/Reports/FourteenMonthReports/FourteenMonthReport.tsx
When an invalid account list id is passed to the 14 month report, the application would redirect to the user's default account list, but the report would be stuck showing an error message. This PR resets the error message and refetches the report data when the account list id changes.
To see the bug, go to https://mpdx.org/accountLists/_/reports/salaryCurrency and see the account list id change in the URL but the report still render an error message.
To see the fix, go to https://fourteen-month-report-redirect.d3dytjb8adxkk5.amplifyapp.com/accountLists/_/reports/salaryCurrency and verify that the reports renders after the account list id changes in the URL.
=> [no-Jira] Refresh 14 month report after account list redirect

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx
In this PR, I allow the user to remove the `Next Increase Ask` date. A Help Scout ticket brought this to my attention.
I also noticed this was happening to the `Start Date` field, which I fixed.
When adding tests, I cleaned up the page.
1. On a contact, click on the `Donations` tab, scroll down and then click on the `Partnership info` tab.
2. Edit partnership to show modal.
3. Set a `Next Increase Ask` date if there isn't one.
4. On the `Next Increase Ask` field, click the calendar icon, and then click `CLEAR`.
5. Click `Save`
On production, doing the above will not remove the `Next Increase Ask` date.
On the preview link, the `Next Increase Ask` date will be removed.
[HelpScout Ticket](https://secure.helpscout.net/conversation/2783501601/1269793?viewId=7296147)
[Jira …
=> Allow user to remove next increase ask date

pages/api/graphql-rest.page.ts
This PR resolves an issue where activity types were not being correctly updated in the Google Calendar integration. The root cause was identified in the handling of a proxy GraphQL query used to fetch the current calendar integration. During this process, lowercase values were converted to uppercase to align with the rest of the website's standards.
However, when sending the calendar integrations back to the REST API, the values needed to be reverted to lowercase. This discrepancy caused issues since the API correctly treats `APPOINTMENT_PHONE_CALL` and `appointment_phone_call` as distinct values. This fix ensures proper conversion and resolves the integration issue.
[Jira Task](https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8491)
[HelpScout …
=> MPDX-8491 - Fix Activity Type Case-Sensitivity Issue in Google Calendar Integration

src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/StreetAutocomplete/StreetAutocomplete.tsx
Disable the default filtering of options in the address autocomplete. Typing an address with a zip code wasn't bringing up any results because the predictions from the Google Maps API don't show the zip code in the description. This will also let users select predictions that don't strictly contain the search substring.
* In production, create a new address and paste "100 Lake Hart Dr, Orlando, FL 32832" into the street search. See that there are not options listed.
* In this preview environment, create a new address and paste "100 Lake Hart Dr, Orlando, FL 32832" into the street search. See that there is an option listed.
https://secure.helpscout.net/conversation/2769079534/1262665?viewId=7296729
=> [HS-1262665] Fix addresses with zip codes not showing predictions

README.md, next.config.ts, src/components/Contacts/ContactDetails/ContactDetailsHeader/DeleteContactModal/ContactSource.graphql, src/components/Contacts/ContactDetails/ContactDetailsHeader/DeleteContactModal/DeleteContactModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/DeleteContactModal/DeleteContactModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.tsx, src/components/Settings/Organization/Contacts/ContactRow/ContactRow.tsx
Remove all hardcoded emails from MPDX and replace them with variables so non-Cru organisations can use their emails without editing the source code.
We don't need to add any new variables to our Amplify as the default values are the ones we use.
This was spotted on Jira task [MPDX-8492](https://jira.cru.org/browse/MPDX-8492) and PR https://github.com/CruGlobal/mpdx-react/pull/1216
=> MPDX-8496 - Replace hard coded emails with env variables

pages/_app.page.tsx
Due to the amount of errors being sent to RollBar regarding hydration and it maxing out our log rate limit, we need to prevent them from being sent to Rollbar.
In this PR, I add a check to prevent any logs regarding hydration from being sent to Rollbar.
We might just be able to get away with ignoring `Minified React error` and not have to worry about `Expected server HTML` since that only shows locally.
=> MPDX-8506 - Prevent hydration errors being sent to RollBar

src/components/Settings/preferences/accordions/CurrencyAccordion/CurrencyAccordion.tsx
The currency preference help text was a copy/paste of the home country preference.
=> [no-Jira] Fix currency preference help text

.github/dependabot.yml, .github/workflows/preview.yml
* Prevent Dependabot from creating PRs for package updates that aren't vulnerable. This config would have prevented PRs like #1235, #1236, #1237, #1238 from being created.
* Update the GitHub workflow to replace all instances of invalid URL characters with dashes in the Amplify Preview URL comment instead of just the first.
@dr-bizz Let me know if you like those PRs, but I was thinking that we ignore them so they don't add noise and we can focus on Dependabot updates that resolve security vulnerabilities.
=> [no-Jira] Disable Dependabot PRs for non-security updates

src/components/Tool/FixSendNewsletter/FixSendNewsletter.test.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx
https://secure.helpscout.net/conversation/2799104265/1278785?viewId=7669074
Problem:
- The user had a contact with a primary person who was deceased. The Fix Send Newsletter page is incorrectly filtering out contacts based on the primary person's deceased status. Contacts should only be hidden if all people in the contact are deceased. When all people are set to deceased, MPDX will automatically update their status to "Never Ask" and then those contacts won't be shown on any "Fix" pages.
Solution: 
- Stop filtering out contacts who have their primary person deceased
=> HS-1278785 Stop filtering out contacts who have their primary person deceased

.pnp.cjs, src/components/Contacts/ContactDetails/ContactDonationsTab/ContactDonationsTab.graphql, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.graphql, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.graphql, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfoMocks.ts
In 2020, we added custom code to the contact details tab for the Switzland Cru. View the [old MPDX Web PR](https://github.com/CruGlobal/mpdx_web/pull/1822/files#diff-e2732a893ad00c26aec49567ffee02a6464e866cb51fb77ddc7e3c82a3397d7d) 
This code only allowed the Switzland Cru organization members to view and edit the "Relationship Code" field since they use this with their MailChimp integration.
In this PR, I have added the field back to the contacts page under the partnership info.
In order for this PR to be deployed, we need some GraphQL work completed. We need to add the field `relationshipCode` as an input under `attributes` on the `updateContact` mutation.
In our code, I have commented out code which is needed, but would break the site otherwise.
**HelpScout**: …
=> MPDX-8511 - Restoring the Relationship Code field on contacts

pages/acceptInvite.page.tsx, pages/acceptInvite.test.tsx, pages/accountLists/[accountListId].page.test.tsx, pages/accountLists/[accountListId].page.tsx, pages/api/utils/pagePropsHelpers.test.ts, pages/api/utils/pagePropsHelpers.ts
The core bug is that `context.req.url` can be `/_next/data/development/accountLists/_.json?accountListId=_` when pushing `/accountLists/_` like the accept invite page does. This is because instead of doing a normal GET request, Next.js loads the props for the new page and rerenders without doing a full-page refresh.
When encountering those props requests, the underscore redirect logic was naively replacing the account list id and returning to a redirect. The fix is to use `context.resolvedUrl` because it gives urls like `/accountLists/_` even during a props request.
I also did some cleanup in the accept invite page and page props helpers.
* `acceptInvite` was treating `!res.ok` from `fetch` as a network error instead of an API error.
* Moved a helper method outside of the `useEffect`.
* …
=> [HS-1284159] Fix accept invite redirect

pages/accountLists/[accountListId]/settings/preferences.page.tsx, src/components/Settings/preferences/accordions/CurrencyAccordion/CurrencyAccordion.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MachineCalculatedGoal.graphql, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.test.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.tsx, src/components/Shared/Forms/FormWrapper.tsx
If the user has a machine calculated goal available, display it in preferences. Also, add a button that resets the user's goal to the machine calculated goal.
[MPDX-8480](https://jira.cru.org/browse/MPDX-8480)
=> [MPDX-8480] Health Indicator preferences page

pages/accountLists/[accountListId]/reports/healthIndicator/index.page.test.tsx, pages/accountLists/[accountListId]/reports/healthIndicator/index.page.tsx, src/components/Dashboard/Dashboard.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.graphql, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorReport.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.graphql, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.test.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.tsx, src/components/Reports/HealthIndicatorReport/MonthlyGoal.graphql, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenuItems.ts
In this PR, I add the MPD HI report page. This uses many of the same charts or graphs of the other PRs, so it doesn't look completely done, but it's not far off.
If you have no data, it shows a message stating there is no data.
The monthly goal graph will also show the HI widget
=> MPDX-8479 HI Report Page & key

pages/api/utils/pagePropsHelpers.test.ts, pages/api/utils/pagePropsHelpers.ts
This PR fixes the error where users find themselves in an endless loop on the login screen. When you are logged out after a certain amount of time, you are redirected to the homepage with the redirect of `/logout`, which, once you log in, you will be automatically logged out.
This PR prevents the redirect for the logout page from being added to the login redirect.
=> Fix login loop from logout redirect

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx
In this PR, I allow the user to edit the `relationship_code` field.
In this PR https://github.com/CruGlobal/mpdx-react/pull/1250, I add the field for only certain users in the Switzerland Cru organization. However, I didn't allow the users to edit the field until the API PR https://github.com/CruGlobal/mpdx_api/pull/2901 was merged.
=> MPDX-8511 - Allowing users to edit the relationship_code field

src/components/Coaching/CoachingList.tsx, src/components/Coaching/LoadCoachingList.graphql
In this PR, I increased the limit of the amount of coaches we fetch on the coaches page from `25` to `100`.
This is only a quick fix. The longer fix would be to make the coaches list into an infinite scroll to ensure all coaches are loaded.
HelpScout Ticket: https://secure.helpscout.net/conversation/2817301546/1288380/
=> MPDX-8515 -  Increase # of coaches fetched

src/lib/apollo/relayStylePaginationWithNodes.tsx
Fix `relayStylePaginationWithNodes` sometimes discarding the first page of data.
=> [no-Jira] Relay pagination data loss

src/components/Coaching/CoachingList.test.tsx, src/components/Coaching/CoachingList.tsx, src/components/Coaching/CoachingRow/CoachingRow.tsx, src/components/Coaching/LoadCoachingList.graphql, src/lib/apollo/cache.ts
As there was a limit on the number of coaches we could grab at one time from the GraphQL, I've implemented the `useFetchAllPages` functionality into the coaches page to ensure all coaches are rendered and not just the first 25.
This PR continues the work done on PR https://github.com/CruGlobal/mpdx-react/pull/1257 Where I adjusted the number of coaches to be fetched from 25 to 100. However, the server limits us to only fetch 50 at a time.
To Test, please impersonate Shelley and navigate to her coaches page. You can find Shelley's email address from this [HelpScout ticket](https://secure.helpscout.net/conversation/2817301546/1288380?viewId=7296147)
=> MPDX-8515 - Fetching all pages on the coaches page

src/components/Reports/FinancialAccountsReport/AccountSummary/AccountSummary.tsx
In this PR, I fix the negative numbers in the Responsibility Center report. As you can view in the HelpScout ticket and in the screenshots below. The new RC report wasn't showing the minus "-" on negative numbers.
HelpScout: https://secure.helpscout.net/conversation/2782787046/1269396?viewId=7296147
Jira: [MPDX-8517](https://jira.cru.org/browse/MPDX-8517)
To test, please impersonate the user "Markiewicz" on the Helpscout ticket.
=> MPDX-8517 - Fix the negative numbers on the Responsibility Center report

src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/AddAddressModal/AddAddressModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/StreetAutocomplete/StreetAutocomplete.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/StreetAutocomplete/StreetAutocomplete.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/CreateMultipleContacts/CreateMultipleContacts.test.tsx
In this PR, I changed how we format the `subpremise` (Apt, Unit or Suite number) on an address.
Before, we always put it in front of the street address formatted like `Apt 100/Street Address`. This is the correct format for the UK, CA and many other countries, but the US and Singapore prefer that `subpremise` be used at the end of the address.
[USPS stated the `subpremise` should be after the street address](https://pe.usps.com/text/pub28/28c2_003.htm)
[Singapore stated the `subpresmise` should be after the address prefixed with a hashtag.](https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/sgpEn.pdf)
[Helpscout](https://secure.helpscout.net/conversation/2827220856/1294018?viewId=7296147)
Jira: [MPDX-8521](https://jira.cru.org/browse/MPDX-8521)
=> MPDX-8521 - Formatting subpremise for US and Singapore addresses

amplify.yml
Strip invalid characters like `/` from the `PREVIEW_URL` when creating preview environments. We're doing this because dependabot creates branches containing slashes. We're using the same logic as the amplify-preview-actions action: https://github.com/CruGlobal/amplify-preview-actions/blob/ba8e23fa3e14151058ba488a9754e154bd1d60ac/entrypoint.sh#L91
These changes successfully created a working preview environment from a branch with slashes in the name: #1264.
=> [no-Jira] Fix PREVIEW_URL in Dependabot preview environments

pages/GetAccountLists.graphql, src/components/AccountLists/AccountLists.test.tsx, src/components/AccountLists/AccountLists.tsx
When the user hasn't set a monthly goal, use the machine calculated goal on the accounts list page.
*Caveat*: If the user's default currency is different from their organization's default, we aren't able to calculate percentages because the goal amount is in one currency and their received and committed amounts are in a different currency.
[MPDX-8538](https://jira.cru.org/browse/MPDX-8538)
=> [MPDX-8538] Default to calculated goal on accounts list page

src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.test.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.tsx
On the preferences page, if the goal isn't set, show the calculated goal in the monthly accordion when the accordion is closed.
[MPDX-8539](https://jira.cru.org/browse/MPDX-8539)
=> [MPDX-8539] Show calculated goal in preferences goal accordion

src/components/Dashboard/MonthlyGoal/MonthlyGoal.test.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.tsx
If the machine calculated goal is being used, add a button that lets the user set their monthly goal in preferences.
* User with HI data
* Set a monthly goal in preferences and test that the Set Monthly Goal button does not appear on the dashboard
* Clear the monthly goal in preferences and test that the Set Monthly Goal button appears on the dashboard and links to the monthly goal accordion in preferences
* User without HI data
* Test that the Set Monthly Goal button does not appear on the dashboard
[MPDX-8540](https://jira.cru.org/browse/MPDX-8540)
=> [MPDX-8540] Add preferences link to monthly goal widget

pages/accountLists/GetDashboard.graphql, pages/accountLists/[accountListId].page.tsx, src/components/Coaching/CoachingDetail/CoachingDetail.tsx, src/components/Coaching/CoachingDetail/LoadCoachingDetail.graphql, src/components/Contacts/ContactDetails/ContactDonationsTab/DonationsGraph/DonationsGraph.graphql, src/components/Dashboard/Dashboard.test.tsx, src/components/Dashboard/Dashboard.tsx, src/components/Dashboard/DonationHistories/DonationHistories.test.tsx, src/components/Dashboard/DonationHistories/DonationHistories.tsx, src/components/Dashboard/DonationHistories/graphData.test.ts, src/components/Dashboard/DonationHistories/graphData.ts, src/components/Reports/DonationsReport/DonationsReport.tsx, src/components/Reports/DonationsReport/GetDonationGraph.graphql
Show the historical support goal in the donations graph.
Testing is a little bit complex because the donations graph shows up in multiple places and each place loads the data independently (it isn't loaded by the graph component itself), so we need to test each place the donations graph is rendered as a HI user and a non-HI user.
* User without HI data
* Go to the donations graph on the dashboard for a user without HI data. Check that the monthly goal is a straight line and is the value set in preferences.
* Go to the donations graph on the donations report page for a user without HI data. Check that the monthly goal is a straight line and is the value set in preferences.
* Go to the donations graph on the coaching page (viewing the user's own data) for a user without HI data. Check that …
=> [MPDX-8542] Show support goal history in donations graph

src/components/Task/Modal/Form/TaskModalHelper.ts
In this PR, I change the frontend to allow an empty string as the default task name.
Initially, we didn't want that, but with the recent changes, certain actions will have an empty string as their detailed task name.
=> MPDX-8457 - Allow empty string as default task name

src/components/Settings/integrations/Mailchimp/MailchimpAccordion.test.tsx, src/components/Settings/integrations/Mailchimp/MailchimpAccordion.tsx
[HS-1320872](https://secure.helpscout.net/conversation/2872011976/1320872?viewId=7669074)
The user is not seeing any buttons to connect a MailChimp account. He has a connection but there is an error with the API key so `validateKey` is set to false.
- Add an error message and disconnect button when `validateKey` is false.
=> [No-Jira] Add Error Message for invalid MailChimp connections

src/components/Task/Modal/Form/TaskModalHelper.ts
In this PR, I have added logic to the default selected Next Action when a result is chosen in the Log Task and Complete Task modal.
Jira ticket: [MPDX-8526](https://jira.cru.org/browse/MPDX-8526)
We no longer set the default Next Action when any of the following IF statements are true:
- The phase is PartnerCare. As mentioned in the Jira task, Scott noted all the Partner Care actions, except for `Letter/Card`. I will confirm that he intends for all of them to behave the same way. It would be unusual if `Letter/Card` didn't.
- The completed action is `Special Gift Appeal`.
We hope this logic will eventually move to the backend. However, since they need to estimate the time and it might not happen within this tertile, I have included it here to expedite task progress. We expect to remove …
=> MPDX-8526 - Prevent the next action being defaulted in certain conditions

src/components/AccountLists/AccountLists.test.tsx, src/components/AccountLists/AccountLists.tsx, src/components/Coaching/CoachingDetail/helpers.test.ts, src/components/Coaching/CoachingDetail/helpers.ts, src/components/Dashboard/MonthlyGoal/MonthlyGoal.test.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.tsx, src/theme.ts
* In the My Accounts grid, indicate when the machine-calculated goal is being displayed.
* Add a tooltip that explains what a machine-calculated goal is and where it comes from.
* In the My Accounts grid and the dashboard, change the color of the goal to an error/warning color when it is machine-calculated.
MPDX-8564
=> [MPDX-8564] Visually indicate machine-calculated goals

src/components/Shared/Filters/FilterPanelTypes.ts
Fix TypeScript error locally from the `addressPrimary` field added to the staging API.
MPDX-8502
=> [MPDX-8502] Fix TypeScript error from new contact filter added in staging

pages/api/Schema/reports/partnerGivingAnalysis/partnerGivingAnalysis.graphql, pages/api/graphql-rest.page.ts
Add new `addressPrimary` contact filter to PGA contact filters. I believe that this needs to be merged immediately after https://github.com/CruGlobal/mpdx_api/pull/2928 because users using the new filter will get GraphQL errors.
MPDX-8502
* Go to stage.mpdx.org
* Go to the Partner Giving Analysis report
* Check the "Address Is Primary" filter under "Contact Location"
* See that there is a GraphQL error
* Go to this PR's preview environment
* Go to the Partner Giving Analysis report
* Check the "Address Is Primary" filter under "Contact Location"
* See that there is **not** a GraphQL error
=> [MPDX-8502] Add addressPrimary filter to ReportContactFilterSetInput

pages/accountLists/[accountListId]/tasks/[[...contactId]].page.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/ContactDetailsTabMailing.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/PartnerAccounts/ContactDetailsPartnerAccounts.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/PartnerAccounts/ContactDetailsPartnerAccounts.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/ContactTaskRow.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskCompleteButton/TaskCompleteButton.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskCompleteButton/TaskCompleteButton.tsx, src/components/Contacts/ContactRow/ContactRow.test.tsx, src/components/Contacts/ContactRow/ContactRow.tsx, src/components/Contacts/ContactUncompletedTasksCount/ContactUncompletedTasksCount.test.tsx, src/components/Contacts/ContactUncompletedTasksCount/ContactUncompletedTasksCount.tsx, src/components/Contacts/StarContactIconButton/StarContactIconButton.test.tsx, src/components/Contacts/StarContactIconButton/StarContactIconButton.tsx, src/components/Layouts/Primary/NavBar/NavBar.test.tsx, src/components/Layouts/Primary/NavBar/NavItem/NavItem.tsx, src/components/Layouts/Primary/NavBar/NavTools/SearchMenuPanel/SearchMenuPanel.tsx, src/components/Layouts/Primary/NavBar/StyledComponents.ts, src/components/Layouts/Primary/TopBar/Items/NotificationMenu/NotificationMenu.tsx, src/components/Layouts/Primary/TopBar/Items/SearchMenu/SearchMenu.tsx, src/components/Task/TaskRow/TaskActionPhase.tsx, src/components/Task/TaskRow/TaskRow.test.tsx, src/components/Task/TaskRow/TaskRow.tsx
Implements all but one of the high-priority accessibility items from the [MPDX Accessibility Roadmap](https://docs.google.com/spreadsheets/d/170qSto7vhGcfQ6ZI5kBoy__rJczxWmFcefouyThiHaY/edit?gid=990418609#gid=990418609). Each commit fixes a single issue.
* Add labels to search, add, and notifications buttons
* Tab through the buttons with VoiceOver enabled
* Test that labels are announced
* Prevent log task and star buttons from opening the contact
* Click the log task and star buttons in the contact list
* Test that the contact doesn't open in the panel
* Make the Log Task icon a true button
* Tab through the contact list to get to the Log Task button with VoiceOver
* Test that it is focusable and its label is announced
* Make more actions keyboard navigable
* Open a contact in the …
=> [no-Jira] High-priority accessibility improvements

pages/accountLists/GetDashboard.graphql, src/components/Dashboard/Dashboard.test.tsx, src/components/Dashboard/DonationHistories/DonationHistories.test.tsx, src/components/Dashboard/DonationHistories/DonationHistories.tsx, src/components/Dashboard/DonationHistories/graphData.test.ts, src/components/Dashboard/DonationHistories/graphData.ts, src/components/Reports/DonationsReport/GetDonationGraph.graphql, src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/useGraphData.test.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/useGraphData.ts
I recently learned that HI data will be generated daily, not monthly like I initially thought. This PR corrects some assumptions in `DonationHistories` that there will only be one HI period per month. Now it selects the latest HI period in the month if there are multiple available.
The greatest complexity is in modifying `useGraphData` to support extrapolation to fill in arbitrary HI periods. HI data will ideally be generated daily, but we need to handle cases where certain days are missing. The code comments and test cases attempt to document in detail the algorithm I'm using, but please let me know if anything can be clarified.
Note that the test data only has one HI period per month. I'm relying on detailed tests to verify that the changes are working correctly since I can't test the …
=> [MPDX-8567] Support multiple HI periods and missing periods

src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/HealthIndicatorGraph.test.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/HealthIndicatorGraph.tsx, src/components/common/LegendReferenceLine/LegendReferenceLine.tsx
Update the "Average" label in the Health Indicator graph to be more descriptive.
I also moved the bold style in the legend from the title to the value.
Before:
After:
Because I think it looks better this way:
Than this way:
I'm going to double-check with Scott, but let me know if you have preferences one way or another.
MPDX-8570
=> [MPDX-8570] Improve the graph average label

src/components/AccountLists/AccountLists.test.tsx, src/components/AccountLists/AccountLists.tsx, src/components/Announcements/AnnouncementAction/AnnouncementAction.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskDate/TaskDate.test.tsx, src/components/Dashboard/DonationHistories/graphData.ts, src/components/Dashboard/MonthlyGoal/MonthlyGoal.test.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.test.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.tsx, src/components/Shared/Forms/Accordions/AccordionItem.tsx, src/components/Shared/Forms/FieldWrapper.tsx, src/lib/healthIndicator.test.ts, src/lib/healthIndicator.ts, src/theme.ts
* Warn if the preferences goal is below the machine-calculated goal
* Warn if the preferences goal has not been updated in the last year
* Extract HI logic into a reusable module
The goal is to implement a UI similar to this mock-up from stakeholders. Note that we are considering language change to something like "system-generated support goal" but that is still being discussed.
MPDX-8566
* On Pedro's account list
* Change the monthly goal in preferences to less than $6,000/month
* Verify that you see a warning above the input while typing and in the accordion header after saving
* Verify that you see a warning on the My Accounts grid, on the dashboard, and on the MPD Health report
* On Pedro's account list
* Change the monthly goal to >$6,000/month
* In `src/lib/healthIndicator.ts` …
=> [MPDX-8566] Preference goal warnings

pages/accountLists/[accountListId]/reports/financialAccounts/[financialAccountId]/entries.page.test.tsx, pages/accountLists/[accountListId]/reports/partnerGivingAnalysis/[[...contactId]].page.test.tsx, pages/accountLists/[accountListId]/settings/Wrapper.tsx, pages/accountLists/[accountListId]/tools/ToolsWrapper.tsx, pages/accountLists/[accountListId]/tools/appeals/appeal/[[...appealId]].page.test.tsx, pages/accountLists/[accountListId]/tools/appeals/appeal/[[...appealId]].page.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.tsx, src/components/Contacts/ContactsMap/ContactsMapPanel.tsx, src/components/Layouts/SidePanelsLayout.tsx, src/components/Shared/Filters/FilterPanel.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenu.tsx, src/components/Tool/Appeal/List/AppealsListFilterPanel/AppealsListFilterPanel.tsx, src/components/Tool/NavToolList/NavToolList.tsx
* Use `aside` element for left and right panels.
* Use `main` element for main content.
* Add labels to left and right panels.
* Go to the Contacts page
* Use Ctrl+Option+Shift+Right/Left to navigate between the left panel, main content, and right panel (if it is moving between navbar items use Ctrl+Option+Shift+Up to navigate out of the navbar)
* After opening a contact, Press Ctrl+Option+Shift+Up twice, then Ctrl+Option+Shift+Right to get to the contact's panel.
Other improvements are possible, but the main areas of the layout are much easier to navigate between in VoiceOver. I'm assuming that other accessibility software has similar methods for jumping between sections of the page.
=> [no-Jira] Improve panel layout navigation

src/components/AccountLists/AccountLists.test.tsx, src/components/AccountLists/AccountLists.tsx, src/components/Dashboard/DonationHistories/graphData.test.ts, src/components/Dashboard/MonthlyGoal/MonthlyGoal.test.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.test.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.tsx
Replace all user-facing labels that say "machine-calculated" with the phrase "NetSuite-calculated". I'm not renaming the comments, variables, or test case names because the GraphQL fields are still reference `machineCalculated`. NetSuite only needs to show up in messaging to the user.
MPDX-8579
=> [MPDX-8579] Replace machine-calculated labels with NetSuite-calculated

src/lib/intlFormat.test.ts, src/lib/intlFormat.ts
Utilize new `trailizingZeroDisplay: 'stripIfInteger'` option to `Intl.NumberFormat` now that use are using node 20+.
=> [no-Jira] Utilize trailizingZeroDisplay: stripIfInteger option

.pnp.cjs, .yarn/cache/@types-uuid-npm-9.0.1-b44e45eb8a-c472b8a77c.zip, __tests__/util/setup.ts, package.json, pages/accountLists/[accountListId]/contacts/flows/setup.page.tsx, pages/api/uploads/upload-person-avatar.page.ts, src/components/Contacts/ContactFlow/contactFlowDefaultOptions.ts, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.test.tsx, src/components/Task/MassActions/EditTasks/MassActionsEditTasksModal.tsx, src/components/Task/Modal/Comments/Form/TaskModalCommentsListForm.tsx, src/components/Task/Modal/Form/Complete/TaskModalCompleteForm.test.tsx, src/components/Task/Modal/Form/Complete/TaskModalCompleteForm.tsx, src/components/Task/Modal/TaskModalProvider.tsx, src/components/Tool/Appeal/Flow/ContactFlow.tsx, yarn.lock
Replace the `uuid` package with the native `crypto.randomUUID()` method.
=> [no-Jira] Replace uuid package with native crypto.randomUUID

src/components/Dashboard/DonationHistories/DonationHistories.tsx
Make the donations goal line dashed for users without health indicator data.
MPDX-8569
* Log into an account without health indicator dat
* Go to the dashboard
* Verify that the goal line in the donations graph is dashed (previously it was only dashed in the legend)
=> [MPDX-8569] Dashed donations goal line

src/components/Reports/HealthIndicatorReport/HealthIndicatorReport.tsx
Update the message shown to users on the Health Indicator report page who don't have HI data with wording received from Shawn and Toncho.
MPDX-8568
* Log into an account without HI data
* Go to the MPD Health report
* Verify that the message matches the updated wording
=> [MPDX-8568] Improve Health Indicator missing data message

src/components/Contacts/ContactFlow/ContactFlow.tsx
Co-authored-by: Caleb Cox <canac@users.noreply.github.com>
MPDX-8441
Fix:
Fix refetch queries object not matching
=> MPDX-8441 Contact Flows not updating

src/components/Loading/Loading.test.tsx, src/components/Loading/Loading.tsx
MPDX-8452
Fix issue with loading indicator not showing while pages are loading.
To see the changes: From the Dashboard, click Contacts in the main menu. You should notice that the loading spinner shows immediately. On Production, this does not happen.
=> MPDX-8452 Tasks loading improvements

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/MassActions/EditFields/MassActionsEditFieldsModal.tsx, src/components/common/LikelyToGiveSelect/LikelyToGiveSelect.test.tsx, src/components/common/LikelyToGiveSelect/LikelyToGiveSelect.tsx
- Corresponds to Jira ticket MPDX-8657 for OKR 41.
- Created a shared component called LikelyToGiveSelect in `src/common/Selects/LikelyToGiveSelect.tsx`
Refactored these files to use the new shared component: 
1. src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx 
2. src/components/Contacts/MassActions/EditFields/MassActionsEditFieldsModal.tsx
=> MPDX-8657 - Created Likely to Give Select shared component

src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactHeaderSection/ContactHeaderStatusSection.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.graphql, src/components/Contacts/ContactPartnershipStatus/ContactLateStatusLabel/ContactLateStatusLabel.test.tsx, src/components/Contacts/ContactPartnershipStatus/ContactLateStatusLabel/ContactLateStatusLabel.tsx, src/components/Contacts/ContactPartnershipStatus/ContactLateStatusLabel/getDonationLateStatus.test.ts, src/components/Contacts/ContactPartnershipStatus/ContactLateStatusLabel/getDonationLateStatus.ts, src/components/Contacts/ContactPartnershipStatus/ContactPartnershipStatus.tsx
[Jira ticket](https://jira.cru.org/browse/MPDX-8690)
- Remediates oversight in the calculation of the late status enums.
=> MPDX-8690 - Remediate oversight over getDonationLateStatus bug

pages/accountLists/[accountListId]/settings/preferences.page.tsx, pages/setup/account.page.tsx, src/common/Autocompletes/AccountListAutocomplete.tsx, src/common/Autocompletes/AccountListAutocomplete/AccountListAutocomplete.test.tsx, src/common/Autocompletes/AccountListAutocomplete/AccountListAutocomplete.tsx, src/components/Settings/preferences/accordions/DefaultAccountAccordion/DefaultAccountAccordion.test.tsx, src/components/Settings/preferences/accordions/DefaultAccountAccordion/DefaultAccountAccordion.tsx
[Jira ticket](https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8668#)
- Extracts DefaultAccountAutocomplete into a reusable, shared component. 
- Modifies DefaultAccountAccordion and account.page.tsx to use this shared component.
- Types of the props being passed in deferred in DefaultAccountAccordion and account.page.tsx when passed into the initial Autocomplete, so they were changed to match in each file.
=> MPDX-8668 - AccountListAutocomplete(s)

amplify.yml
Today (7/25/2025) all Amplify build started failing with the following error message:
```
npm install -g --quiet @aws-amplify/cli bower cypress grunt-cli hugo-extended vuepress yarn
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: stylus-loader@3.0.2
npm warn Found: stylus@undefined
npm warn node_modules/vuepress/node_modules/stylus
npm warn
npm warn Could not resolve dependency:
npm warn peer stylus@">=0.52.4" from stylus-loader@3.0.2
npm warn node_modules/vuepress/node_modules/stylus-loader
npm warn   stylus-loader@"^3.0.2" from @vuepress/theme-default@1.9.10
npm warn   node_modules/vuepress/node_modules/@vuepress/theme-default
npm error code ETARGET
npm error notarget No matching version found for stylus@^0.54.8.
npm error notarget In most cases you or one of your …
```
=> [no-Jira] Install yarn manually

src/components/Tool/Appeal/AppealsContext/AppealsContext.test.tsx, src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx, src/components/Tool/Appeal/List/AppealsListFilterPanel/AppealsListFilterPanel.test.tsx, src/components/Tool/Appeal/List/AppealsListFilterPanel/AppealsListFilterPanel.tsx, src/components/Tool/Appeal/List/ContactsList/ContactsList.test.tsx, src/components/Tool/Appeal/List/ContactsList/ContactsList.tsx
In the appeals list, storing the appeal status filter in the URL was a major source of race conditions and the filters and URL getting out of sync. This PR eliminates those issues by storing the appeal status in state instead of in the URL.
This PR is highly-dependent on work in #1343, but I'm putting it in a separate PR for ease of review since it is fairly self-contained.
MPDX-8667
=> [MPDX-8667] Eliminate race conditions in appeals filter state

src/components/Reports/FinancialAccountsReport/Context/FinancialAccountsContext.tsx, src/components/Shared/Filters/FilterPanel.tsx, src/components/common/UrlFiltersProvider/UrlFiltersProvider.test.tsx, src/components/common/UrlFiltersProvider/UrlFiltersProvider.tsx
In this PR, I replaced the `clearSearchTerm()` function with a new `clearFilters()` function in `UrlFiltersProvider.tsx`. This new function resets both the filters and search term stored in context, allowing multiple components to easily clear all search-related values with a single function call. I also updated all references to `clearSearchTerm()` in other files to use `clearFilters()` instead.
=> MPDX-8676 Expose clear filters

src/components/Layouts/SidePanelsLayout.tsx, src/components/Reports/GoalCalculator/GoalCalculator.tsx
This PR creates the goal calculator layout without needing to have `<SidePanelsLayout>` nested inside of another `<SidePanelsLayout>`. I also simplified a few of the components and styles.
I also added vertical flexbox layout to the `<main>` component so that pages can set `flex: 1` on their content to make them fill all available space.
=> [no-Jira] Remove nesting of SidePanelsLayout in goal calculator

amplify.yml
This reverts commit 459fff393fdfc08cc3cf2a4773eb6eef4937c1d8.
The workaround in #1374 was necessary because npm removed the `stylus` package, but has since restored it: https://www.bleepingcomputer.com/news/security/npm-accidentally-removes-stylus-package-breaks-builds-and-pipelines/. The workaround is no longer necessary.
=> [no-Jira] Revert "Install yarn manually"

src/components/Reports/GoalCalculator/GoalCalculator.tsx, src/components/Reports/GoalCalculator/Shared/GoalCalculatorContext.tsx
Perform some cleanup of the goal calculator context. I removed `categories` from the context dependency array because it will be a new array on every render and was breaking memoization.
=> [no-Jira] Clean up goal calculator context

pages/api/Schema/CoachingAnswerSets/coachingAnswerSets.graphql, pages/api/Schema/CoachingAnswerSets/resolvers.ts, pages/api/graphql-rest.page.ts, src/components/Coaching/CoachingDetail/WeeklyReport/WeeklyReport.graphql, src/components/Coaching/CoachingDetail/WeeklyReport/WeeklyReport.test.tsx, src/components/Coaching/CoachingDetail/WeeklyReport/WeeklyReport.tsx, src/components/Dashboard/ThisWeek/WeeklyActivity/WeeklyReportModal/WeeklyReportModal.graphql
A HelpScout user is having trouble seeing their current coaching answer set. The UI is blindly loading the most-recent answer set, which is pulling their empty answer set from Germany Cru. The UI needs to pass in an organizationId filter to only pull the current answer set from their salary organization.
[HS-1419450](https://secure.helpscout.net/conversation/3026279923/1419450/)
Depends on CruGlobal/mpdx_api#2978.
* Go to an account with coaching answer sets set up (you can impersonate me if you need one)
* Verify that the current coaching answer set loads by checking that the "Fill out weekly report" button is present on the dashboard.
=> [HS-1419450] Load salary organization coaching answer set

pages/accountLists/[accountListId]/reports/goalCalculator/index.page.tsx, src/components/Reports/GoalCalculator/GoalCalculator.test.tsx, src/components/Reports/GoalCalculator/GoalCalculator.tsx, src/components/Reports/GoalCalculator/GoalCalculatorHelper.ts, src/components/Reports/GoalCalculator/HouseholdExpenses/HouseholdExpenses.tsx, src/components/Reports/GoalCalculator/MinistryExpenses/Steps/MileageStep/MileageStepRightPanelComponent/MileageStepRightPanelComponent.tsx, src/components/Reports/GoalCalculator/Shared/GoalCalculatorContext.tsx
Start instructions for household expenses to the top of the form and right panels for specific categories. Also, I started writing some tests for `GoalCalculator`. We need more, but I have the scaffolding for more and wrote tests for the new functionality I added. I also corrected the order of the household expenses and ministry expenses icons in the left sidebar.
MPDX-8720
=> [MPDX-8720] Add household expenses instructions

.github/copilot-instructions.md
Adds basic GitHub Copilot instructions. From my research, these instructions are included with every prompt, so they need to be as lean as possible to avoid filling up the context window. There's probably more we could add, but for now I'm adding instructions to correct behavior I've seen multiple times from GitHub Copilot:
* Using `npm` instead of `yarn`
* Using the wrong command to run `tsc`
* Creating components with a default export
* Adding `await` to `userEvent.click()` (that is correct in v14, but we are on v13)
=> [no-Jira] Add initial GitHub Copilot instructions

src/components/Helpjuice/Helpjuice.test.tsx, src/components/Helpjuice/Helpjuice.tsx, src/components/Helpjuice/widget.mock.ts
The Helpjuice Swifty widget is rendering links to articles as relative URLs like `/question/123`. Clicking on them takes users to `https://mdpx.org/question/123`, which 404s.
We can work around this by adding the Helpjuice domain to those URLs.
* Test 1
* Open the Helpjuice widget
* Click on the "The Contacts Tab" article
* Scroll down and click on the "Contacts Views" link
* Check that you are taken to HelpDucks and not to an MPDX page
* Test 2
* Open the Helpjuice widget
* Search for "MailChimp Sync" and click on that article
* Check that the links to mailchimp.com and mpdx.org are left unchanged and open correctly
[HelpScout ticket](https://secure.helpscout.net/conversation/3042913312/1431211)
=> [HS-1431211] Turn Helpjuice article links into absolute URLs

pages/accountLists/[accountListId]/reports/mpgaIncomeExpenses/index.page.tsx, src/components/Reports/MPGAIncomeExpensesReport/MPGAIncomeExpensesReport.test.tsx, src/components/Reports/MPGAIncomeExpensesReport/MPGAIncomeExpensesReport.tsx, src/components/Reports/MPGAIncomeExpensesReport/ReportsStaffExpenses.graphql
Remove the `accountId` argument from `reportsStaffExpenses`. Should be merged immediately after https://github.com/CruGlobal/mpdx_api/pull/2994.
=> [no-Jira] Remove accountId argument from reportsStaffExpenses

src/components/Reports/GoalCalculator/CalculatorSettings/SettingsSectionList.test.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/SettingsSectionList.tsx, src/components/Reports/GoalCalculator/GoalCalculatorTestWrapper.tsx, src/components/Reports/GoalCalculator/Shared/familySections.test.ts, src/components/Reports/GoalCalculator/Shared/familySections.ts, src/components/Reports/GoalCalculator/SharedComponents/ExpensesStep/ExpensesStep.tsx
Instead of using a static list, populate the settings sidebar with the categories in the "special" family. #1421 has already updated the settings page to render the tables for the special family's categories.
MPDX-8798
=> [MPDX-8798] Populate settings sidebar with special family categories

codegen.yml, src/components/Tool/FixSendNewsletter/FixSendNewsletter.test.tsx
I noticed that upgrading prettier to v3 in #1420 stopped formatting our files generated by gql-codegen. v3 apparently respects `.prettierignore` even when paths are manually specified. We have to disable `.prettierignore` by passing `--ignore-path=""`.
* Run `yarn gql`
* Find any `.generated.ts` file
* Check whether it has been  has been formatted with `prettier` (a missing trailing newline is evidence that it was **not** formatted)
=> [no-Jira] Run prettier on ignored gql codegen files

src/components/Reports/MPGAIncomeExpensesReport/MPGAIncomeExpensesReport.test.tsx, src/components/Reports/MPGAIncomeExpensesReport/MPGAIncomeExpensesReport.tsx, src/components/Reports/MPGAIncomeExpensesReport/ReportsStaffExpenses.graphql, src/components/Reports/SavingsFundTransfer/IntroPage/IntroPage.tsx, src/components/Reports/SavingsFundTransfer/TransfersPage/TransfersPage.test.tsx, src/components/Reports/SavingsFundTransfer/TransfersPage/TransfersPage.tsx, src/components/Reports/SavingsFundTransfer/mockData.ts, src/components/Reports/StaffAccount.graphql, src/components/Reports/StaffSavingFund/StaffSavingFundContext.tsx, src/components/Reports/StaffSavingFund/StaffSavingFundLayout.tsx, src/hooks/useFilteredFunds.test.ts
`staffAccount` is a query that will return a staff account's **id**, **name**, and **status**. This query will be used to fetch this information instead of pulling it from the report queries. This PR will address the MPGA Monthly Income Expenses and Savings Fund Transfer reports. It should also include updating the Staff Expenses report, however, that is in a separate PR.
Staff Expenses: [#1375](https://github.com/CruGlobal/mpdx-react/pull/1375) 
**Waiting for PR to merge**
Depends on: [MPDX-8801](https://github.com/CruGlobal/mpdx_api/pull/2995)
Urls:
MPGA: `/reports/mpgaIncomeExpenses`
Savings Fund: `/reports/staffSavingFund`
=> MPDX-8807 Use staff account query in reports

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.tsx
This `@ts-ignore` isn't needed anymore. Maybe upgrading TypeScript the last time fixed it.
=> [no-Jira] Remove unneeded ts-ignore directive

.github/workflows/ci.yml
It is common for UI PRs to be dependent on an API PR that is in staging, but not in production. In CI, our GraphQL codegen tasks target production to ensure that we don't merge code that depends on GraphQL APIs not yet available in staging. But when the API PR is still in staging, that makes all of our CI checks fail immediately before we get a chance to see whether our tests pass or whether the PR has lint errors.
This PR introduces a "Staging API" label for PRs that are using GraphQL APIs only available in staging. It makes CI run GraphQL codegen against the staging GraphQL API so we can see if our tests pass, but it also prevents those PRs from merging with the Staging API label. Once the API PR is in production, developers should remove the "Staging API" to unblock merging. …
=> [no-Jira] Make "Staging API" run codegen against the staging API
