CruGlobal/mpdx-react

src/components/Contacts/ContactFilters/ContactFilters.stories.tsx, src/components/Contacts/ContactsHeader/ContactsHeader.stories.tsx, src/components/Contacts/ContactsTable/ContactsTable.stories.tsx
This PR is just to move all of the contact Stories under the Contact section.
=> Move contact stories under Contacts

src/components/Layouts/Primary/AddFab/AddFab.stories.tsx, src/components/Layouts/Primary/AddFab/AddFab.test.tsx, src/components/Task/Drawer/CommentList/CommentList.mock.tsx, src/components/Task/Drawer/CommentList/CommentList.stories.tsx, src/components/Task/Drawer/CommentList/CommentList.test.tsx, src/components/Task/Drawer/CommentList/CommentList.tsx, src/components/Task/Drawer/CommentList/Form/Form.stories.tsx, src/components/Task/Drawer/CompleteForm/CompleteForm.mock.tsx, src/components/Task/Drawer/CompleteForm/CompleteForm.stories.tsx, src/components/Task/Drawer/CompleteForm/CompleteForm.test.tsx, src/components/Task/Drawer/ContactList/ContactList.mock.tsx, src/components/Task/Drawer/ContactList/ContactList.stories.tsx, src/components/Task/Drawer/ContactList/ContactList.test.tsx, src/components/Task/Drawer/ContactList/ContactList.tsx, src/components/Task/Drawer/Drawer.stories.tsx, src/components/Task/Drawer/Drawer.test.tsx, src/components/Task/Drawer/Form/Form.mock.tsx, src/components/Task/Drawer/Form/Form.stories.tsx, src/components/Task/Drawer/Form/Form.test.tsx, src/components/Task/Home/Home.stories.tsx, src/components/Task/Home/Home.test.tsx, src/components/Task/List/List.mock.tsx, src/components/Task/List/List.stories.tsx, src/components/Task/List/List.test.tsx, src/components/Task/List/List.tsx
Fixed the Storybook tests that were producing errors.  Also added error messages to the components and wrote tests for them.
=> MPDX-6920: Fix Storybook Renders

src/components/Contacts/Tasks/ContactTasks.graphql, src/components/Contacts/Tasks/ContactTasks.test.tsx
https://jira.cru.org/browse/MPDX-6962
=> MPDX-6958 Contact Task query

src/components/Task/Drawer/CommentList/Form/Form.stories.tsx
This is to fix a Lint issue that I keep recieving
=> fix form List issue

src/components/Constants/LoadConstants.graphql, src/components/Constants/UseApiConstants.test.tsx
This will fix the issue that occurred due to the new schema change in the GraphQl
=> Fix scheme error

src/components/Task/Drawer/Form/Form.stories.tsx
Hopefully this fixes the main build.
=> Fix task drawer form mock typings

src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/ContactDetailsOther.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/ContactDetailsOther.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/ContactOther.graphql
=> MPDX-6975 : Other contact detail tab section

next.config.js, pages/api/auth/[...nextauth].page.ts, pages/login.page.tsx
- Fixes issues with VERCEL_URL being the Vercel deployment url instead of the domain name
=> Set SITE_URL and NEXTAUTH_URL based on branch first

src/components/Contacts/ContactDetails/ContactDetails.tsx, src/components/Contacts/ContactDetails/ContactDontationsTab/ConatctDonationsTab.test.tsx, src/components/Contacts/ContactDetails/ContactDontationsTab/ContactDonationsTab.graphql, src/components/Contacts/ContactDetails/ContactDontationsTab/ContactDonationsTab.stories.tsx, src/components/Contacts/ContactDetails/ContactDontationsTab/ContactDonationsTab.tsx
https://jira.cru.org/browse/MPDX-6973
This is the Outline for the Contact Donations Tab
=> MPDX-6973 contact donation tab base

src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.graphql, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/AddMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/AddMenu.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/CreateContact/CreateContact.graphql, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/CreateContact/CreateContact.stories.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/CreateContact/CreateContact.test.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/CreateContact/CreateContact.tsx
Breaking up https://jira.cru.org/browse/MPDX-6998 into smaller prs. This one focuses on adding/creating a contact.
=> MPDX-6998-Add-Contact-Mutation

src/components/Contacts/ContactDetails/ContactDetailsTab/Tags/ContactTags.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/Tags/ContactTags.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Tags/ContactTags.tsx
Had to do this autocomplete component a little bit different than how the others are used throughout the app because of the design for contact tags. But happy with how it turned out. Feel free to try it out and let me know what you think! If you see anything weird in the code, please ask questions 🙂
=> MPDX-7030-Add-Autocomplete-To-ContactTags

codegen-server.yml, pages/api/Schema/TaskAnalytics/taskAnalytics.graphql, pages/api/Schema/index.ts, pages/api/Schema/reports/fourteenMonth/datahandler.ts, pages/api/Schema/reports/fourteenMonth/fourteenMonth.graphql, pages/api/Schema/reports/fourteenMonth/resolvers.ts, pages/api/Schema/scalarResolvers.ts, pages/api/Schema/scalars.graphql, pages/api/graphql-rest.page.ts
I tried to make the schema better. Let me know what you think :) Specifically:
1. Merged donor infos to be able to load both donation info and contact info at the same time.
2. Tried to remove all the converted stuff and make it conditional on what type of `currencyType` is requested.
3. Remove maximum which isn't used by the UI
4. Compute average and minimum totals for each currency group
5. Compute salaryCurrencyTotal as it's always used in tooltip and conditionally return it as the total
This thing is complex so I probably missed something maybe related to currency conversion. I tried to compare it to the existing one and I think it's close. I'll test it more when we have some UI to directly compare.
To test:
1. Sign in at https://mpdx-react-4zvrhx9do-cru.vercel.app/login.
2. Go to …
=> Add 14 Month Report to GraphQL schema

.eslintrc.js, pages/accountLists/[accountListId]/contacts/[[...contactId]].page.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.tsx, src/components/Contacts/ContactFilters/ContactFilters.stories.tsx, src/components/Contacts/ContactFilters/ContactFilters.test.tsx, src/components/Contacts/ContactFilters/ContactFilters.tsx, src/components/Contacts/ContactsHeader/ContactsHeader.test.tsx, src/components/Contacts/ContactsHeader/ContactsHeader.tsx, src/components/Contacts/ContactsTable/ContactsTable.tsx, src/components/Layouts/Primary/Primary.tsx, src/components/Layouts/Primary/TopBar/TopBar.tsx, src/components/Layouts/SidePanelsLayout.tsx, src/components/Task/Drawer/Drawer.tsx, src/theme.ts
I think I got everything working. Feel free to play with the preview and let me know what you think, if you see any way to make this simpler, or see any issues with it. The CSS is a little complex.
I haven't made any attempt to make the content inside each of the 3 panels responsive yet. There are some horizontal scroll bars inside the panels still. That can be another ticket.
John made this proof of concept which was helpful :)
https://codepen.io/j2trumpet/pen/dd1ead3747b95b897e696c6ecf7ef6d2?editors=0100
=> MPDX-7017: Make Contacts Responsive

src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx, src/components/common/Modal/Modal.stories.tsx, src/components/common/Modal/Modal.test.tsx, src/components/common/Modal/Modal.tsx
After discussion with others, I made some changes to the generic modal component. Also added comments for the props, which is pretty neat when viewing in VSCode.
=> Cleanup-Modal-Component

src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/ContactTaskRow.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/ContactTaskRow.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskCommentsButton/TaskCommentsButton.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.test.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.tsx, src/components/Task/Drawer/Drawer.test.tsx, src/components/Task/Drawer/Drawer.tsx
This is another pr addressing something found while investigating what was left to do on the contact details page.
=> Add Functionality to Buttons on Task Tab in Contact Details

src/components/Reports/ExpectedMonthlyTotalReport/Empty/ExpectedMonthlyTotalReportEmpty.test.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Empty/ExpectedMonthlyTotalReportEmpty.tsx, src/components/Reports/ExpectedMonthlyTotalReport/ExpectedMonthlyTotalReport.test.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Header/ExpectedMonthlyTotalReportHeader.test.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Table/ExpectedMonthlyTotalReportTable.test.tsx
Fixing the Lint and test errors.  We'll add more tests after the Rest to GraphQL work is done.
=> MPDX-7040 fix

src/components/Contacts/ContactDetails/ContactDetails.tsx, src/components/Contacts/ContactDetails/ContactNotesTab/ContactNotesTab.graphql, src/components/Contacts/ContactDetails/ContactNotesTab/ContactNotesTab.tsx
I got a component created! However, I have no idea how to hook it up to data saving and retrieval. I imagine it has something to do with the `accountListId={accountListId} contactId={contactId}` props that are being passed to the other contact info components, but even just trying to add them to my component threw an error. I also don't know if there are any styles that you guys have been applying to form fields other than the default MUI styling. Can you guys help me with finishing this up?
=> MPDX-6976: Contact Details - Notes tab

src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/ContactDetailsTabPeople.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/ContactDetailsTabPeople.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/ContactPeople.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetails.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetailsModal.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetailsModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditContactDetailsModal/EditContactDetailsModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/EditPersonModal.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/EditPersonModal.stories.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/EditPersonModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/EditPersonModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/ModalSectionDeleteIcon/ModalSectionDeleteIcon.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/PersonBirthday/PersonBirthday.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/PersonEmail/PersonEmail.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/PersonName/PersonName.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/PersonPhoneNumber/PersonPhoneNumber.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/PersonShowMore/PersonShowMore.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/EditPersonModal/PersonSocials/PersonSocials.tsx
This... was a lot haha. Passing ```formikProps``` around was actually very easy and nice to use! What took some figuring out was how to update nested values like social accounts, email addresses, etc. This doesn't include logic to add new emails, phone numbers, social media accounts but it will be handled in a separate pr. With what I've figured out here, it should hopefully be straightforward. Please ask questions, especially around the formik stuff if anything looks strange 🙂 
Also a note, there are now two different modals that update different things. There is `EditContactDetailsModal` that allows the user to update the contact name and primary person(updating primary person logic will be in a future pr, currently not available in the schema).  Then there is ```EditPersonModal``` that …
=> MPDX-6998-Edit-Contact-Details-Logic

pages/api/Schema/index.ts, pages/api/Schema/reports/designationAccounts/datahandler.ts, pages/api/Schema/reports/designationAccounts/designationAccounts.graphql, pages/api/Schema/reports/designationAccounts/resolvers.ts, pages/api/graphql-rest.page.ts
This PR is rest to graphql for designation accounts.
=> rest to graphql for designation accounts

src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactHeaderSection/ContactHeaderStatusSection.test.tsx
I have recurringly noticed that test coverage was low for this specific component. Decided to quickly add tests for all cases of status in order to raise code cov.
=> Additional-Contact-Header-Status-Test

src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/ContactMailing.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactMailingModal/EditContactMailingModal.graphql, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactMailingModal/EditContactMailingModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactMailingModal/EditContactMailingModal.tsx
I'll be breaking the logic for editing mailing details into two prs. This pr focuses on details that are not related to addresses. The other pr will be for editing contact addresses.
=> MPDX-6998-Edit-Contact-Mailing-Details

pages/api/Schema/CoachingAnswerSets/coachingAnswerSets.graphql, pages/api/Schema/CoachingAnswerSets/dataHandler.ts, pages/api/Schema/CoachingAnswerSets/resolvers.ts, pages/api/Schema/index.ts, pages/api/graphql-rest.page.ts
Providing Coaching Answer Sets data using REST to GraphQL.
=> MPDX-6909: Coaching Answer Sets GraphQL

pages/accountLists.page.tsx, pages/accountLists/[accountListId].page.tsx, pages/accountLists/[accountListId]/tasks.page.tsx, src/components/App/Provider.tsx, src/components/App/rootReducer.test.ts, src/components/App/rootReducer.ts, src/components/Layouts/Primary/Primary.stories.tsx, src/components/Layouts/Primary/Primary.test.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/AddMenu.stories.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.stories.tsx, src/components/Layouts/Primary/TopBar/Items/NotificationMenu/NotificationMenu.stories.tsx, src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.stories.tsx, src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/SearchMenu/SearchMenu.stories.tsx, src/components/Layouts/Primary/TopBar/TopBar.stories.tsx, src/components/Task/List/List.test.tsx
I just decided to break it up into pieces so it doesn't have to wait for the rest of the logic to be removed. The main issue I'm having with the other parts is fixing the tests.
=> Remove-Breadcrumb-From-useApp

src/components/Tool/Home/Tool.tsx
put the nextlink inside the card to remove warning
=> fixed a console warning cause by the tool component

pages/api/Schema/index.ts
I was missing to add the document and resolver to schemas.
=> add financial account schema

pages/accountLists/GetDashboard.graphql, pages/accountLists/[accountListId]/contacts/Contacts.graphql, src/components/Dashboard/ThisWeek/GetThisWeek.graphql, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/GetNewsletterContacts.graphql, src/components/Task/Drawer/ContactList/TaskDrawerContactList.graphql
- https://github.com/CruGlobal/mpdx_api/pull/2426
=> Use contactsFilter input

pages/api/Schema/index.ts, pages/api/Schema/reports/entryHistories/datahandler.ts, pages/api/Schema/reports/entryHistories/entryHistories.graphql, pages/api/Schema/reports/entryHistories/resolvers.ts, pages/api/graphql-rest.page.ts
This PR is a rest-to-gql for entry histories of financial accounts.
=> Rest to gql entry histories of financial accounts

src/components/Reports/AccountsListLayout/List/ListItem/Chart/Chart.test.tsx, src/components/Reports/AccountsListLayout/List/ListItem/Chart/Chart.tsx, src/components/Reports/AccountsListLayout/List/ListItem/ListItem.test.tsx, src/components/Reports/AccountsListLayout/List/ListItem/ListItem.tsx, src/components/Reports/ResponsibilityCentersReport/GetEntryHistories.graphql, src/components/Reports/ResponsibilityCentersReport/GetFinancialAccounts.graphql, src/components/Reports/ResponsibilityCentersReport/ResponsibilityCentersReport.test.tsx, src/components/Reports/ResponsibilityCentersReport/ResponsibilityCentersReport.tsx, src/components/Reports/ResponsibilityCentersReport/ResponsibilityCentersReport.type.ts
This PR is for a functionality to set a financial account active and show a chart which refers to the monthly averages.
=> set active financial account & show chart for monthly averages

pages/accountLists/[accountListId]/tools/fixSendNewsletter.page.tsx, src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx, src/components/Tool/FixSendNewsletter/NoContacts.tsx, src/components/Tool/FixSendNewsletter/StyledInput.tsx
Same as the fix commitment info UI, just basic for now, will update later
=> Fix send newsletter basic UI

pages/accountLists/[accountListId]/reports/donations.page.tsx, src/components/Reports/AccountsListLayout/Header/Header.tsx, src/components/Reports/DonationsReport/DonationsReport.stories.tsx, src/components/Reports/DonationsReport/DonationsReport.test.tsx, src/components/Reports/DonationsReport/DonationsReport.tsx
Updated donations report by adding side menu and others...
=> update donations report including side menu

src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.test.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx, src/components/Tool/Home/Home.tsx, src/components/Tool/Home/ToolList.ts, src/hooks/useCurrentToolId.ts
Dropdown menu for tools. There was an issue with the translations, I left a specific comment for that section
=> Navbar tools dropdown

pages/accountLists/[accountListId]/tools/mergeContacts.page.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddreses.tsx, src/components/Tool/MergeContacts/Contact.tsx, src/components/Tool/MergeContacts/MergeContacts.tsx, src/components/Tool/MergeContacts/NoContacts.tsx
Basic ui for merging contacts
Mobile View:
=> Merge contatcts basic UI

pages/accountLists/[accountListId]/tools/appeals.page.tsx, pages/accountLists/[accountListId]/tools/fixCommitmentInfo.page.tsx, pages/accountLists/[accountListId]/tools/fixEmailAddresses.page.tsx, pages/accountLists/[accountListId]/tools/fixMailingAddresses.page.tsx, pages/accountLists/[accountListId]/tools/fixPhoneNumbers.page.tsx, pages/accountLists/[accountListId]/tools/fixSendNewsletter.page.tsx, src/components/Tool/FixPhoneNumbers/Contact.test.tsx, src/components/Tool/FixPhoneNumbers/Contact.tsx, src/components/Tool/FixPhoneNumbers/DeleteModal.test.tsx, src/components/Tool/FixPhoneNumbers/DeleteModal.tsx, src/components/Tool/FixPhoneNumbers/FixPhoneNumbers.test.tsx, src/components/Tool/FixPhoneNumbers/FixPhoneNumbers.tsx, src/components/Tool/FixPhoneNumbers/NoContacts.test.tsx, src/components/Tool/FixPhoneNumbers/NoContacts.tsx
=> Fix phone numbers UI

src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx, src/components/Tool/FixSendNewsletter/GetInvalidNewsletter.graphql, src/components/Tool/FixSendNewsletter/NoContacts.tsx
Fix newsletter page should now use real contact data. Some if it missing though because it needs pagination.
=> Fix send newsletter gql

src/components/Tool/FixMailingAddresses/AddressModal.tsx, src/components/Tool/FixMailingAddresses/Contact.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx, src/components/Tool/FixMailingAddresses/GetInvalidAddresses.graphql, src/components/Tool/FixMailingAddresses/NoContacts.tsx
This page should now load the correct contacts
=> Fix mailing addresses graphql

src/components/Tool/FixCommitmentInfo/Contact.tsx, src/components/Tool/FixCommitmentInfo/FixCommitmentInfo.tsx, src/components/Tool/FixCommitmentInfo/GetInvalidStatuses.graphql, src/components/Tool/FixCommitmentInfo/InputOptions/ContactTags.ts, src/components/Tool/FixCommitmentInfo/InputOptions/Frequencies.ts
This page should load the actual data now, but no pagination yet
=> Fix commitment info graphql

src/components/Tool/Appeal/AddAppealForm.tsx, src/components/Tool/Appeal/CreateAppeal.graphql
The contact tags thing doesnt do anything yet but adding the appeal works
=> Mpdx 7103 new appeal

pages/accountLists/[accountListId]/tools/appeals.page.tsx, pages/accountLists/[accountListId]/tools/fixCommitmentInfo.page.tsx, pages/accountLists/[accountListId]/tools/fixEmailAddresses.page.tsx, pages/accountLists/[accountListId]/tools/fixMailingAddresses.page.tsx, pages/accountLists/[accountListId]/tools/fixSendNewsletter.page.tsx, src/components/Tool/Appeal/Appeals.test.tsx, src/components/Tool/Appeal/Appeals.tsx, src/components/Tool/FixCommitmentInfo/FixCommitmentInfo.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddreses.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx, src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx
Moved accountListId retrieval up on level to prevent errors, there are PRs out for some of the other pages so I'll just do those individually
=> Fixed error for missing accountListId

src/components/Tool/FixCommitmentInfo/Contact.tsx
fixed console warning from select input in fix commitment info page
=> Fixed console warning on fix commitment info page

src/components/Tool/Appeal/Appeal.test.tsx, src/components/Tool/Appeal/Appeal.tsx, src/components/Tool/Appeal/Appeals.test.tsx, src/components/Tool/Appeal/Appeals.tsx, src/components/Tool/Appeal/ChangePrimaryAppeal.graphql
Added ability to change your primary appeal
=> Mpdx 7104 change primary appeal

src/components/Layouts/Primary/NavBar/NavBar.test.tsx, src/components/Layouts/Primary/NavBar/NavBar.tsx, src/components/Layouts/Primary/NavBar/NavItem/NavItem.tsx, src/components/Layouts/Primary/NavBar/NavTools/AddMenuPanel/AddMenuPanel.test.tsx, src/components/Layouts/Primary/NavBar/NavTools/AddMenuPanel/AddMenuPanel.tsx, src/components/Layouts/Primary/NavBar/NavTools/NavTools.test.tsx, src/components/Layouts/Primary/NavBar/NavTools/NavTools.tsx, src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.test.tsx, src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.tsx, src/components/Layouts/Primary/NavBar/NavTools/SearchMenuPanel/SearchMenuPanel.test.tsx, src/components/Layouts/Primary/NavBar/NavTools/SearchMenuPanel/SearchMenuPanel.tsx, src/components/Layouts/Primary/Primary.test.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/AddMenu.tsx, src/components/Layouts/Primary/TopBar/Items/NotificationMenu/NotificationMenu.tsx, src/components/Layouts/Primary/TopBar/TopBar.test.tsx, src/components/Layouts/Primary/TopBar/TopBar.tsx
I added nav tools from topbar to navbar for the responsiveness.
=> add nav tools & responsive

src/components/Coaching/AppealProgress/AppealProgress.stories.tsx, src/components/Coaching/AppealProgress/AppealProgress.test.tsx, src/components/Coaching/AppealProgress/AppealProgress.tsx, src/components/Coaching/CoachingDetail/CoachingDetail.stories.tsx, src/components/Coaching/CoachingDetail/CoachingDetail.test.tsx, src/components/Coaching/CoachingDetail/CoachingDetail.tsx, src/components/Coaching/CoachingRow/CoachingRow.tsx
Simplify Appeal Progress to reuse logic.
=> Mpdx 7182   create reusable appeal progress

pages/accountLists/[accountListId]/contacts/[[...contactId]].page.tsx, pages/accountLists/[accountListId]/tasks/[[...contactId]].page.tsx
Just a small fix for a crashing but when filters/mass selection is used
=> fixed crashing bug when data is undefined

__tests__/pages/api/MpdxWebHandoff.test.ts, __tests__/util/globalSetup.ts, __tests__/util/setup.ts, src/components/Contacts/MassActions/Exports/exportRest.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportPhysical/ExportPhysical.test.tsx, src/components/HandoffLink/HandoffLink.test.tsx, src/components/Settings/integrations/Google/GoogleAccordion.test.tsx, src/components/Settings/integrations/Mailchimp/MailchimpAccordion.test.tsx, src/components/Settings/integrations/Organization/OrganizationAccordion.test.tsx, src/components/Settings/integrations/Prayerletters/PrayerlettersAccordion.test.tsx, src/components/common/AppSettings/AppSettingsProvider.test.tsx
Devs were experiencing some tests failing due to the variable SITE_URL not being defined in their `.env` file. I've added the `SITE_URL` to the globalSetup test file to ensure all tests pass without relying on the dev's local `.env`.
=> No-Jira - Ensuring devs don't need to add SITE_URL to their .env files

src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/Item/Item.tsx, src/components/Shared/MultiPageLayout/MultiPageMenu/MultiPageMenuItems.ts
Fix auth links on the preferences side menu going to the auth.mpdx.org (sidekiq & Backend Admin)
=> noJira - Fixed auth links on MPDX Preferences side menu

README.md, next.config.js, pages/_document.page.tsx
This PR adds environment information to the RUM data so not all data is lumped together in Datadog.
=> No-Jira - Add environment information to RUM

.github/workflows/preview-close.yml, .github/workflows/preview.yml, amplify.yml
This PR seeks to re-enable Amplify previews now that this is a public repo.
=> No-Jira - Re-enable Previews

src/components/DataDog/DataDog.tsx, src/lib/dataDog.test.ts, src/lib/dataDog.ts
* Add the user's language preference to the DataDog session so that we can better understand how many of our users use MPDX in English vs in other languages.
https://jira.cru.org/browse/MPDX-7894
=> [MPDX-7894] Add user's language preference to the DataDog session

src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/AddAddressModal/AddAddressModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/AddAddressModal/DynamicAddAddressModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/DynamicEditContactAddressModal.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditContactAddressModal/EditContactAddressModal.tsx, src/components/Tool/FixMailingAddresses/Contact.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddresses.test.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx, src/components/Tool/FixMailingAddresses/FixMailingAddressesMock.ts
In this PR, I added a model for adding a mailing address, cleaned up the add button, and made some improvements to `AddAddressModal`, which I then did on `EditContactAddressModal`. I've also added tests for editing, deleting, and adding an address.
I also cleaned up the FixMailingAddress component, switched the modal state props to separate state values, and refactored the modal open/close handling.
=> MPDX-7935 add mailing address

pages/accountLists/[accountListId]/tools/fixEmailAddresses/[[...contactId]].page.test.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddressPerson.test.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddressPerson.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddresses.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddressesMocks.ts, src/components/Tool/FixEmailAddresses/GetInvalidEmailAddresses.graphql
MPDX-7956
Added a Contact Drawer that opens when the user clicks on the contact's name
Used a graphQl query for 'contactId'
- [X ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [X ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ X] I have requested a review from another person on the project
=> MPDX-7956 Fix Email Addresses Contact Name Link

src/components/Contacts/ContactDetails/ContactDetailsTab/Tags/ContactTags.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Tags/ContactTags.tsx, src/components/Contacts/MassActions/AddTags/MassActionsAddTagsModal.test.tsx, src/components/Contacts/MassActions/AddTags/MassActionsAddTagsModal.tsx
Jira Ticket: Mpdx-7583
-Before when adding duplicate tags they just wouldn't save upon refresh
-Created an error snackbar and deleted the tag when a user tries to create a duplicate tag
-In the contact list view this will apply if any selected contacts have the tag the user is trying to add
- [ X] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ X] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ X] I have requested a review from another person on the project
=> Mpdx-7583 duplicate tags

src/components/Settings/integrations/Google/GoogleAccordion.test.tsx, src/components/Settings/integrations/Google/GoogleAccordion.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&projectKey=MPDX&view=detail&selectedIssue=MPDX-8054#
Adding a warning message to tell users to give MPDX all the permissions when connecting a Google Account to MPDX.
=> MPDX-8054 Add google auth warning message

pages/accountLists/[accountListId]/tools/fixEmailAddresses/[[...contactId]].page.test.tsx, src/components/InfiniteList/InfiniteList.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddresses.graphql, src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx, src/components/Tool/FixEmailAddresses/FixEmailAddresses.tsx, src/lib/apollo/cache.ts
[Jira](https://jira.cru.org/browse/MPDX-7420)
This PR adds an infinite list integration with the Fix Email Addresses tool. It does some improvements to the `InfiniteList` component to remove the flicker and allow for removing the gray background when we don't want it.
=> MPDX-7420 - Fix Email Addresses - add pagination

src/components/Contacts/ContactFlow/ContactFlow.tsx, src/components/Contacts/ContactFlow/ContactFlowDragLayer/ContactFlowDragLayer.tsx, src/components/Contacts/ContactFlow/ContactFlowDragLayer/useAutoScroll.test.ts, src/components/Contacts/ContactFlow/ContactFlowDragLayer/useAutoScroll.ts
* In the flows view, when dragging near the edges, automatically horizontally scroll the columns to make it easier to drag contacts to off-screen columns on narrow screens
[MPDX-8075](https://jira.cru.org/browse/MPDX-8075)
=> [MPDX-8075] Horizontally scroll flows view when dragging near the edges

src/components/Contacts/ContactDetails/ContactDetails.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/ContactDetailsOther.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/EditContactOtherModal/EditContactOtherModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/Other/EditContactOtherModal/EditContactOtherModal.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/PartnershipInfo.tsx, src/components/Contacts/ContactDetails/ContactReferralTab/ContactReferralTab.test.tsx, src/components/Contacts/ContactDetails/ContactReferralTab/ContactReferralTab.tsx, src/components/Dashboard/ThisWeek/Referrals/Referrals.tsx, src/components/Shared/Filters/FilterListItemMultiselect.tsx, src/components/Shared/Filters/FilterPanel.mocks.ts, src/components/Shared/Filters/FilterPanel.test.tsx, src/components/Shared/Filters/FilterPanel.tsx, src/components/Shared/Filters/helpers.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8135&sprint=1259#
- Rename Referrals to Connections
=> MPDX-8135-replace-referrals

src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/Tool/MergeContacts/MergeContacts.tsx, src/components/Tool/MergeContacts/StickyConfirmButtons.tsx, src/components/Tool/MergePeople/MergePeople.tsx, src/components/Tool/StyledFabLoading.tsx, src/components/Tool/TntConnect/TntConnect.tsx, src/components/Tool/styledComponents.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8161&sprint=1259#
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8160&sprint=1259#
- Adding Card styling to TntConnect and Fix Send Newsletter
- Improving styles and placement of the Loading indicator on Merge tools
=> MPDX-8160 Tools-style-changes

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/MassActions/EditFields/MassActionsEditFieldsModal.tsx, src/components/Layouts/Primary/TopBar/Items/AddMenu/Items/CreateMultipleContacts/CreateMultipleContacts.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Table/ExpectedMonthlyTotalReportTable.test.tsx, src/components/Reports/ExpectedMonthlyTotalReport/Table/ExpectedMonthlyTotalReportTable.tsx, src/components/Reports/FourteenMonthReports/FourteenMonthReport.tsx, src/components/Reports/FourteenMonthReports/Layout/Table/Table.tsx, src/hooks/useContactPartnershipStatuses.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8170&sprint=1259#
- With the API changing contact statuses to lowercase snakecase, fix the Contact's status format
- Use the translated Phase name
=> MPDX-8170-fix-statuses

src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
Focus the amount field in the commitment modal.
[MPDX-8189](https://jira.cru.org/browse/MPDX-8189)
=> [MPDX-8189] Focus amount field in commitment modal

src/components/Task/Modal/Form/Inputs/PhaseTags/PhaseTags.tsx, src/components/Task/Modal/Form/TaskModalHelper.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8168&sprint=1259#
- Make lowercase before comparing tags so they are acurately shown as checked.
=> MPDX-8168 Fix suggested tags

src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/PersonEmail/PersonEmail.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/PersonEmail/PersonEmail.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/Items/PersonModal/PersonModal.test.tsx, src/components/Contacts/MassActions/Exports/Emails/MassActionsExportEmailsModal.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/ExportEmail/ExportEmail.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.test.tsx, src/components/Dashboard/ThisWeek/NewsletterMenu/MenuItems/LogNewsLetter/LogNewsletter.tsx, src/components/Layouts/Primary/TopBar/Items/NotificationMenu/Item/Item.test.tsx, src/components/Layouts/Primary/TopBar/Items/NotificationMenu/Item/Item.tsx, src/utils/functions/getLocalizedSendNewsletter.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8169&sprint=1259#
- Rename Email Newsletter to Digital Newsletter
=> MPDX-8169 Rename to Digital Newsletter

src/components/Tool/Appeal/Modals/UpdateDonationsModal/DonationTable/DonationTable.tsx, src/components/Tool/Appeal/Modals/UpdateDonationsModal/UpdateDonationsModal.test.tsx
In the update donations modal, cross out the appeal name on donations that will removed from that appeal because the user deselected them.
[MPDX-8194](https://jira.cru.org/browse/MPDX-8194)
=> [MPDX-8194] Cross out donations that will be removed from the appeal

src/components/Contacts/ContactFlow/ContactFlowColumn/ContactFlowColumn.test.tsx, src/components/Contacts/ContactFlow/ContactFlowColumn/ContactFlowColumn.tsx
In this PR, I fixed the Flows starred filtered view to ensure when the starred filter is clicked; it filters the columns.
=> MPDX-8223 - Fixed starred filter Contact Flows view

pages/api/Schema/reports/fourteenMonth/datahandler.ts, pages/api/Schema/reports/fourteenMonth/fourteenMonth.graphql, src/components/Reports/FourteenMonthReports/Layout/Table/Table.tsx, src/components/Reports/FourteenMonthReports/Layout/Table/helpers.test.ts, src/components/Reports/FourteenMonthReports/useCsvData.test.ts, src/components/Reports/FourteenMonthReports/useCsvData.ts
* Convert contact statuses from the REST API into `StatusEnum` values.
* Localize contact statuses in the 14 month reports.
[MPDX-8221](https://jira.cru.org/browse/MPDX-8221)
=> [MDPX-8221] Convert status string to `StatusEnum`

src/lib/data/languages.ts, src/lib/i18n.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8269&sprint=1268#
- Add new languages
- Add fallback languages
Manual testing
- Tested to make sure the Angular language selection matches the React language code so the Language preference gets updated.
- Tested that each new language actually finds the language file and translates things. 
- I found that Ukranian and Swiss German translation files are all in English.
=> Add languages

src/components/Coaching/CoachingDetail/Activity/Activity.tsx, src/components/Dashboard/ThisWeek/Appeals/Appeals.test.tsx, src/components/Dashboard/ThisWeek/Appeals/Appeals.tsx, src/components/Layouts/Primary/NavBar/NavBar.tsx, src/components/Layouts/Primary/NavBar/NavItem/NavItem.tsx, src/components/Layouts/Primary/Primary.test.tsx, src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx, src/components/Settings/integrations/Google/GoogleAccordion.test.tsx, src/components/Settings/integrations/Google/GoogleAccordion.tsx, src/components/Settings/integrations/integrationsHelper.ts
* Replace tools handoff links with links to the React pages
Part of [MPDX-8270](https://jira.cru.org/browse/MPDX-8270)
=> [MPDX-8270] Tools Go Live 🎉

src/components/Tool/Appeal/Flow/ContactFlow.test.tsx, src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.test.tsx, src/components/Tool/Appeal/Flow/ContactFlowColumn/ContactFlowColumn.tsx, src/components/Tool/Appeal/Flow/ContactFlowDropZone/ContactFlowDropZone.test.tsx, src/components/Tool/Appeal/Flow/ContactFlowDropZone/ContactFlowDropZone.tsx
Localize the appeal status when dragging contacts between columns.
[MPDX-8339](https://jira.cru.org/browse/MPDX-8339)
=> [MPDX-8339] Localize appeal status when dragging

pages/accountLists/[accountListId]/reports/financialAccounts/[[...financialAccount]].page.test.tsx, src/components/Reports/FinancialAccountsReport/AccountTransactions/AccountTransactions.test.tsx, src/components/Reports/FinancialAccountsReport/AccountTransactions/AccountTransactions.tsx, src/components/Reports/FinancialAccountsReport/AccountTransactions/AccountTransactionsMocks.ts, src/components/Reports/FinancialAccountsReport/FinancialAccounts/FinancialAccounts.test.tsx, src/components/Reports/FinancialAccountsReport/FinancialAccounts/FinancialAccountsMocks.ts, src/components/Reports/FinancialAccountsReport/Header/Header.test.tsx, src/components/Reports/FinancialAccountsReport/Header/Header.tsx
I've added tests to the transactions page and components. I was meant to add these tests to a previous PR but due to time I had to launch without the tests.
I also fix a few errors which have been raised in a helpscout ticket:
https://secure.helpscout.net/conversation/2732656504/1242288?folderId=7296147
=> RC: Add tests to transactions page and components

README.md
Document Google Maps API key environment variable.
https://secure.helpscout.net/conversation/2733915985/1242646?viewId=320673
=> [HS-1242646] Document GOOGLE_MAPS_API_KEY environment variable

pages/accountLists/[accountListId]/contacts/ContactsWrapper.test.tsx, pages/accountLists/[accountListId]/contacts/ContactsWrapper.tsx, pages/accountLists/[accountListId]/contacts/[[...contactId]].page.tsx, pages/accountLists/[accountListId]/reports/partnerGivingAnalysis/[[...contactId]].page.test.tsx, pages/accountLists/[accountListId]/reports/partnerGivingAnalysis/[[...contactId]].page.tsx, pages/accountLists/[accountListId]/tasks/Tasks.test.tsx, pages/accountLists/[accountListId]/tasks/[[...contactId]].page.tsx, pages/accountLists/[accountListId]/tasks/useTasksContactContext.ts, pages/accountLists/[accountListId]/tools/appeals/AppealsWrapper.tsx, src/components/Contacts/ContactsContext/ContactsContext.test.tsx, src/components/Contacts/ContactsContext/ContactsContext.tsx, src/components/Contacts/ContactsMap/ContactsMap.test.tsx, src/components/Contacts/ContactsMap/ContactsMap.tsx, src/components/Contacts/MassActions/Merge/MassActionsMergeModal.test.tsx, src/components/Shared/Filters/FilterPanel.test.tsx, src/components/Shared/Filters/NullState/NullState.tsx, src/components/Shared/MassActions/ContactsMassActionsDropdown.test.tsx, src/components/Tool/Appeal/AppealDetails/AppealsDetailsPage.tsx, src/components/Tool/Appeal/AppealsContext/AppealsContext.test.tsx, src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx, src/components/Tool/MergeContacts/MergeContacts.test.tsx, src/components/Tool/MergePeople/MergePeople.test.tsx, src/hooks/useDebounce.test.ts, src/hooks/useDebounce.ts
The root cause of buggy routing behavior throughout the app is that changes to the router don't seem to take effect immediately. For example, when clearing filters, one `useEffect` removes `filters` from the query and another `useEffect` removes `searchTerm` from the query. However, when the second effect runs, the change to the filters haven't propagated yet, and it ends up adding the filters back to the URL.
My solution, which has seemed to work well on the contacts page, is to put state that affects the URL (like filters and the search query) into a `useState`. Changes to that state will update immediately. The context wrapper then updates the URL as the state changes. Because the state variables are the source of truth instead of the URL, delays in the URL updating don't cause …
=> [MPDX-8360] Fix changing contact filters reloading the page

pages/login.page.test.tsx, pages/login.page.tsx, src/components/Contacts/ContactsLeftPanel/ContactsLeftPanel.test.tsx, src/components/Welcome/Welcome.stories.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8389&sprint=1282#
- Replace hardcoded help link with env
=> MPDX-8389 Replace hardcoded help link

pages/accountLists/[accountListId]/contacts/ContactsWrapper.tsx, pages/accountLists/[accountListId]/reports/partnerGivingAnalysis/[[...contactId]].page.test.tsx, pages/accountLists/[accountListId]/reports/partnerGivingAnalysis/[[...contactId]].page.tsx, pages/accountLists/[accountListId]/tasks/[[...contactId]].page.tsx, src/hooks/useUserPreference.test.tsx, src/hooks/useUserPreference.ts
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8408&sprint=1282#
- Make the task and contact filter panel open state save to user options.
- Make the filter panel on the PGA report always show like on Angular.
=> MPDX-8408 Filter Panel User Options

src/components/Coaching/AppealProgress/AppealProgress.tsx, src/components/Coaching/CoachingDetail/Activity/AppealProgress.tsx, src/components/Shared/MinimalSpacingTooltip.tsx, src/components/StyledProgress/StyledProgress.test.tsx, src/components/StyledProgress/StyledProgress.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8417&sprint=1282#
- Add below committed and below received amount to thermometer bar.
- Add tooltips to explain each of the amounts
=> MPDX-8417 Add missing remaining amounts and tooltips to coaching thermometer

pages/accountLists/[accountListId]/contacts/flows/setup.page.tsx, src/components/Announcements/AnnouncementBanner/AnnouncementBanner.tsx, src/components/Contacts/ContactDetails/ContactDetails.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/ContactTaskRow.tsx, src/components/Contacts/ContactDetails/ContactTasksTab/ContactTaskRow/TaskCompleteButton/TaskCompleteButton.tsx, src/components/Contacts/ContactFlow/ContactFlowSetup/Header/ContactFlowSetupHeader.tsx, src/components/Layouts/Primary/TopBar/TopBar.tsx, src/components/Layouts/SidePanelsLayout.tsx, src/components/Shared/alertBanner/AlertBanner.tsx, src/components/Task/Modal/Comments/Item/TaskModalCommentListItem.tsx, src/components/Task/TaskRow/TaskActionPhase.tsx, src/components/Task/TaskRow/TaskRow.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8426#
- On mobile, show task row details on 3 lines
- Adjust spacing
- Make mobile nav menu button larger
- Make comments show line breaks
=> MPDX-8426 Mobile Improvements

dependabot.yml
Configure dependabot to request a review from our team on new PRs so that we have better visibility into important ones to merge. Also check for vulnerabilities more frequently.
=> [no-Jira] Dependabot PR reviews

src/components/Helpjuice/Helpjuice.tsx
https://secure.helpscout.net/conversation/2768871462/1262512?viewId=7669074
- Make links open in new tab
=> HS-1262512 Make helpducks link open in new tab

src/components/Dashboard/Dashboard.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.test.tsx, src/components/Dashboard/MonthlyGoal/MonthlyGoal.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.graphql, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.test.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/WidgetStat/WidgetStat.tsx, src/components/StyledProgress/StyledProgress.test.tsx, src/components/StyledProgress/StyledProgress.tsx
In this PR, I have created the Health Indicator widget and add it to the dashboard. The data I use is the last item in the `healthIndicatorData`array, which I fetch using the `HealthIndicatorWidget` GQL query. _(I'm unsure if that is correct, but I'm going with it for now.)_
I've added tests for the HI widget and Monthly Goal Components.
**Process Bar Component:** Switched `makeStyles()` to `styled()` components to allow me to make the HI process bar thinner.
**Monthly Goal Component:** If HI data is present, make it responsive with the HI widget.
=> MPDX-8478 - Add MPD-HI Card to Dashboard

src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/StreetAutocomplete/StreetAutocomplete.tsx
https://secure.helpscout.net/conversation/2787902057/1272111?viewId=7669074
- Keep formik in sync by setting the street to the full description before changing it back
=> HS-1272111 Add Address Auto-Fill bug

src/components/Contacts/ContactDetails/ContactDetailsHeader/DeleteContactModal/ContactSource.graphql, src/components/Contacts/ContactDetails/ContactDetailsHeader/DeleteContactModal/DeleteContactModal.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsHeader/DeleteContactModal/DeleteContactModal.tsx
In this PR, I'm fixing very small changes which I missed on PR https://github.com/CruGlobal/mpdx-react/pull/1227
- Adding an extra line on the email
- Changing the GraphQL query name
=> MPDX-8496 - Slight improvements to email text and GQL query name

src/components/Tool/FixEmailAddresses/FixEmailAddresses.graphql, src/components/Tool/FixPhoneNumbers/GetInvalidPhoneNumbers.graphql
https://secure.helpscout.net/conversation/2796561763/1276961?viewId=7669074
- Update graphql request to filter our people who are deceased or inactive.
=> HS-1276961 Remove deceased people from fix phone/email suggestions

src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/ConsistencyExplanation.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/DepthExplanation.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/OwnershipExplanation.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/SuccessExplanation.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorWidget/HealthIndicatorWidget.tsx, src/components/Shared/Forms/Accordions/AccordionItem.tsx, src/components/Shared/Forms/Accordions/GroupedAccordion.tsx
Add detailed explanations to health indicator items on the HI report. The explanations were copied from [this doc](https://docs.google.com/document/d/1BXHxSCvkRwoFEZcokASMebiZWz6hYC6eZGZmGvFlUmk/edit).
[MPDX-8541](https://jira.cru.org/browse/MPDX-8541)
=> [MPDX-8541] Add health indicator explanations

src/components/Contacts/ContactDetails/ContactDonationsTab/DonationsGraph/DonationsGraph.tsx
In this PR, I made UI/UX edits to make the donations graph that appears on the contact's donations tab easier to understand the data.
- Updating the legend labels.
- Changing the colour from Cru yellow to Cru blue to make the bars and text more visible. It was hard for me to read, so it might be really hard for others to read.
Jira: https://jira.cru.org/browse/MPDX-8543
=> MPDX-8543 ImproveUI/UX for contact's donation graph

README.md, onesky/download.js
In this PR, I remove the documentation and AMplify command to install LFS, as it's not needed
Jira: MPDX-8572
=> MPDX-8572 - Remove Git LFS Install as not needed

src/components/Layouts/Primary/TopBar/Items/NotificationMenu/Item/Item.tsx, src/components/Layouts/Primary/TopBar/Items/NotificationMenu/NotificationMenu.tsx, src/lib/apollo/relayStylePaginationWithNodes.tsx
https://secure.helpscout.net/conversation/2896873270/1337456?viewId=7669074
The notification count is not being updated when a notification is clicked or when 'Mark All as Read' is clicked.
- Remove optimisticResponse checks
- Fix cache changes (CC)
=> [HS-1337456] Fix Notification Count

pages/accountLists/[accountListId].page.test.tsx, pages/accountLists/[accountListId]/settings/preferences.page.test.tsx, src/components/Dashboard/DonationHistories/DonationHistories.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.graphql, src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MachineCalculatedGoal.graphql, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.test.tsx, src/components/Settings/preferences/accordions/MonthlyGoalAccordion/MonthlyGoalAccordion.tsx
Stop loading all HI periods when only the latest period is needed.
Also, update `DonationHistories` to use `getHealthIndicatorInfo` to centralize as much HI logic as possible in that helper function.
MPDX-8567
=> [MPDX-8567] Optimize Health Indicator queries

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx
Issue:
We get this error when clearing the pledge amount.
Changes:
- Check to ensure pledgeAmount is not an empty string
=> No-Jira Check to ensure pledgeAmount is not an empty string

pages/accountLists/[accountListId]/contacts/ContactsWrapper.test.tsx, pages/accountLists/[accountListId]/contacts/ContactsWrapper.tsx, src/components/Contacts/ContactDetails/ContactDetailContext.tsx, src/components/Contacts/ContactDetails/ContactDetails.test.tsx, src/components/Contacts/ContactDetails/ContactDetailsTab/People/ContactDetailsTabPeople.tsx
https://jira.cru.org/secure/RapidBoard.jspa?rapidView=3&view=detail&selectedIssue=MPDX-8450#
- If there is a personId in the URL, switch to the Contact Details tab and open the person modal
- When switching to a different contact, remove the personId from the URL
=> MPDX-8450 Read contact detail person from URL

src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/useGraphData.test.tsx, src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/useGraphData.ts
Exclude missing health indicator components from the weighted average when they are unavailable. Also, add a more detailed explanation to the health indicator that describes how it is calculated.
MPDX-8582
=> [MPDX-8582] Adjust calculations when indicators are absent

src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.test.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/lib/intlFormat.test.ts, src/lib/intlFormat.ts
MPDX-7827
- Add setRawPledgeAmount state to format the display value to 2 decimal places. But use setFieldValue to set the actual pledgeAmount.
- Fix tests
=> MPDX-7827 Show 2 Decimal places on Pledge Amount

pages/accountLists/[accountListId]/settings/integrations/index.page.test.tsx, src/components/Settings/integrations/Mailchimp/MailchimpAccordion.test.tsx, src/components/Settings/integrations/Mailchimp/MailchimpAccordion.tsx, src/components/Settings/integrations/Mailchimp/Modals/DeleteMailchimpModal.tsx
From their website, the correct branding is "Mailchimp" not "MailChimp". We had some spellings both ways. I did a simple find and replace to correct it.
=> [no-Jira] Replace MailChimp with Mailchimp

src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx
A user found that if you click an appeal from the appeals list, then try to select all contacts, the selected count would be higher than the number of contacts in the list. This is because `allExcludedContacts` loaded once because `contactsFilters.appealStatus` wasn't set, then stopped loading because `contactsFilters.appealStatus` changed to `active`, causing that query to be skipped. However, `allContactIds` was still including those excluded contacts because `allExcludedContactsPrevious` contained the excluded contacts from before the query was skipped.
The fix is to ignore excluded contacts if the query is skipped (i.e. if we are in the list view). Excluded contacts should only be added to `allContactIds` in the flows view.
[HelpScout …
=> [HS-1394249] Fix contacts count in appeal contacts list

src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditMailingInfoModal/EditMailingInfoModal.tsx, src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx, src/components/Contacts/MassActions/EditFields/MassActionsEditFieldsModal.tsx, src/components/Tool/FixSendNewsletter/Contact.tsx, src/components/common/NewsletterSelect/NewsletterSelect.test.tsx, src/components/common/NewsletterSelect/NewsletterSelect.tsx
[MPDX-8659 Jira ticket](https://jira.cru.org/browse/MPDX-8659)
The following are combined to use one Select as they all use the SendNewsLetterEnum:
- src/components/Contacts/ContactDetails/ContactDetailsTab/Mailing/EditMailingInfoModal/EditMailingInfoModal.tsx
- src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx
- src/components/Contacts/MassActions/EditFields/MassActionsEditFieldsModal.tsx
- src/components/Tool/FixSendNewsletter/Contact.tsx
=> MPDX-8659 -  Newsletter Selects

pages/accountLists/[accountListId]/reports/goalCalculator/[[...contactId]].page.tsx
The goal calculator doesn't need to open contacts, so we can remove the contact right panel from the layout to streamline the code and decrease the bundle size.
=> [no-Jira] Remove contact right panel from goal calculator

pages/accountLists/[accountListId]/reports/goalCalculator/index.page.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/InformationStep/InformationStep.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/OneTimeGoalsStep/OneTimeGoalsStep.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/SpecialIncomeStep/SpecialIncomeStep.tsx, src/components/Reports/GoalCalculator/GoalCalculator.tsx, src/components/Reports/GoalCalculator/MinistryExpenses/Steps/MileageStep/MileageStep.tsx, src/components/Reports/GoalCalculator/MinistryExpenses/Steps/MileageStep/MileageStepRightPanelComponent/MileageStepRightPanelComponent.tsx, src/components/Reports/GoalCalculator/Shared/GoalCalculatorContext.tsx
Previously, we had only one category on each view. This PR puts all categories for a step in the same view.
MPDX-8713
=> [MPDX-8713] Put all categories on the same page

src/components/Reports/GoalCalculator/CalculatorSettings/Steps/InformationStep/InformationStepForm/InformationStepPersonalForm.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/OneTimeGoalsStep/OneTimeGoalsHelperPanel/OneTimeGoalsHelperPanel.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/OneTimeGoalsStep/OneTimeGoalsStep.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/OneTimeGoalsStep/OneTimeGoalsStepForm/OneTimeGoalsStepForm.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/SpecialIncomeStep/SpecialIncomeStep.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Steps/SpecialIncomeStep/SpecialIncomeStepForm/SpecialIncomeStepForm.tsx, src/components/Reports/GoalCalculator/HouseholdExpenses/HouseholdExpenses.tsx, src/components/Reports/GoalCalculator/MinistryExpenses/Steps/MileageStep/MileageStep.tsx, src/components/Reports/GoalCalculator/MinistryExpenses/Steps/MileageStep/MileageStepForm/MileageStepForm.tsx
Several UI tweaks to match the Google Sheet more closely and improve the wording in a couple places.
MPDX-8736
=> [MPDX-8736] Goal calculator UI tweaks to match Sheet

src/components/Reports/GoalCalculator/SummaryReport/MpdGoal/MpdGoalHeaderCards/MpdGoalHeaderCards.test.tsx, src/components/Reports/GoalCalculator/SummaryReport/MpdGoal/MpdGoalHeaderCards/MpdGoalHeaderCards.tsx, src/components/Reports/GoalCalculator/SummaryReport/SummaryReport.tsx
MPDX-8735
- Creates the MPD Goal header cards that display the user's goal amount and the percentage of their progress.
- I am thinking the directory structure for the page needs to be improved. I might suggest to make a new PR to do that.
=> MPDX-8735 - MPD Goal Header

src/components/Reports/GoalCalculator/CalculatorSettings/Categories/SettingsCategory/GoalCalculation.graphql, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/SettingsCategory/SettingsCategory.test.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/SettingsCategory/SettingsCategory.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/SettingsSectionList.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/SettingsStep.tsx, src/components/Reports/GoalCalculator/GoalCalculatorTestWrapper.tsx, src/components/Reports/GoalCalculator/GoalCard/GoalCard.test.tsx, src/components/Reports/GoalCalculator/GoalCard/GoalCard.tsx, src/components/Reports/GoalCalculator/GoalsList/GoalCalculations.graphql, src/components/Reports/GoalCalculator/GoalsList/GoalsList.test.tsx, src/components/Reports/GoalCalculator/GoalsList/GoalsList.tsx, src/components/Reports/GoalCalculator/Shared/GoalCalculation.graphql
[Jira ticket](https://jira.cru.org/browse/MPDX-8769)
- Adds front end text field to allow users to enter a goal title.
- Additionally sorts GoalCards by updatedAt
=> MPDX-8769: Goal Calculator title input frontend

src/components/Reports/GoalCalculator/CalculatorSettings/Categories/Autosave/AutosaveTextField.test.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/Autosave/AutosaveTextField.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/Autosave/useSaveField.test.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/Autosave/useSaveField.ts, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/InformationCategory/InformationCategory.test.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/InformationCategory/InformationCategory.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/InformationCategory/InformationCategoryForm/InformationCategoryFinancialForm.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/InformationCategory/InformationCategoryForm/InformationCategoryPersonalForm.tsx, src/components/Reports/GoalCalculator/CalculatorSettings/Categories/SettingsCategory/SettingsCategory.test.tsx, src/components/Reports/GoalCalculator/GoalCalculatorTestWrapper.tsx, src/components/Reports/GoalCalculator/Shared/GoalCalculation.graphql
Set up autosave for geographic location, family size, and benefits plan fields.
MPDX-8837
=> [MPDX-8837] Save geographic location, family size, and benefits plan fields

pages/accountLists/[accountListId]/reports/staffExpense.page.tsx, src/components/Reports/StaffExpenseReport/AccountInfoBox/AccountInfoBox.test.tsx, src/components/Reports/StaffExpenseReport/AccountInfoBox/AccountInfoBox.tsx, src/components/Reports/StaffExpenseReport/AccountInfoBox/AccountInfoBoxSkeleton.test.tsx, src/components/Reports/StaffExpenseReport/AccountInfoBox/AccountInfoBoxSkeleton.tsx, src/components/Reports/StaffExpenseReport/BalanceCard/BalanceCard.test.tsx, src/components/Reports/StaffExpenseReport/BalanceCard/BalanceCard.tsx, src/components/Reports/StaffExpenseReport/BalanceCard/BalanceCardSkeleton.test.tsx, src/components/Reports/StaffExpenseReport/BalanceCard/BalanceCardSkeleton.tsx, src/components/Reports/StaffExpenseReport/DownloadButtonGroup/DownloadButtonGroup.test.tsx, src/components/Reports/StaffExpenseReport/DownloadButtonGroup/DownloadButtonGroup.tsx, src/components/Reports/StaffExpenseReport/DownloadButtonGroup/downloadReport.test.tsx, src/components/Reports/StaffExpenseReport/DownloadButtonGroup/downloadReport.tsx, src/components/Reports/StaffExpenseReport/GetStaffExpense.graphql, src/components/Reports/StaffExpenseReport/Helpers/StaffReportEnum.ts, src/components/Reports/StaffExpenseReport/Helpers/formatDate.test.tsx, src/components/Reports/StaffExpenseReport/Helpers/formatDate.tsx, src/components/Reports/StaffExpenseReport/Helpers/useLocalizedCategory.tsx, src/components/Reports/StaffExpenseReport/SettingsDialog/SettingsDialog.test.tsx, src/components/Reports/StaffExpenseReport/SettingsDialog/SettingsDialog.tsx, src/components/Reports/StaffExpenseReport/StaffExpenseReport.test.tsx, src/components/Reports/StaffExpenseReport/StaffExpenseReport.tsx, src/components/Reports/StaffExpenseReport/Tables/EmptyReportTable.test.tsx, src/components/Reports/StaffExpenseReport/Tables/EmptyReportTable.tsx, src/components/Reports/StaffExpenseReport/Tables/PrintTables.test.tsx, src/components/Reports/StaffExpenseReport/Tables/PrintTables.tsx, src/components/Reports/StaffExpenseReport/Tables/StaffReportTable.test.tsx, src/components/Reports/StaffExpenseReport/Tables/StaffReportTable.tsx, src/components/Reports/StaffExpenseReport/filterTransactions.test.tsx, src/components/Reports/StaffExpenseReport/filterTransactions.tsx
[Jira ticket](https://jira.cru.org/browse/MPDX-8587)
This covers subtickets:
- MPDX-8691
- MPDX-8694
- MPDX-8692
- MPDX-8693
URL: `/reports/staffExpense`
- **Filtering by category not currently implemented, waiting on realistic data**
=> MPDX-8587 - Staff Expense Report page and tables
